<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title></title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.13 and GitBook 2.6.7" />

  <meta property="og:title" content="" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />








<script>
/* ========================================================================
 * Bootstrap: transition.js v3.3.7
 * http://getbootstrap.com/javascript/#transitions
 * ========================================================================
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */


+function ($) {
  'use strict';

  // CSS TRANSITION SUPPORT (Shoutout: http://www.modernizr.com/)
  // ============================================================

  function transitionEnd() {
    var el = document.createElement('bootstrap')

    var transEndEventNames = {
      WebkitTransition : 'webkitTransitionEnd',
      MozTransition    : 'transitionend',
      OTransition      : 'oTransitionEnd otransitionend',
      transition       : 'transitionend'
    }

    for (var name in transEndEventNames) {
      if (el.style[name] !== undefined) {
        return { end: transEndEventNames[name] }
      }
    }

    return false // explicit for ie8 (  ._.)
  }

  // http://blog.alexmaccaw.com/css-transitions
  $.fn.emulateTransitionEnd = function (duration) {
    var called = false
    var $el = this
    $(this).one('bsTransitionEnd', function () { called = true })
    var callback = function () { if (!called) $($el).trigger($.support.transition.end) }
    setTimeout(callback, duration)
    return this
  }

  $(function () {
    $.support.transition = transitionEnd()

    if (!$.support.transition) return

    $.event.special.bsTransitionEnd = {
      bindType: $.support.transition.end,
      delegateType: $.support.transition.end,
      handle: function (e) {
        if ($(e.target).is(this)) return e.handleObj.handler.apply(this, arguments)
      }
    }
  })

}(jQuery);
</script>
<script>
/* ========================================================================
 * Bootstrap: collapse.js v3.3.7
 * http://getbootstrap.com/javascript/#collapse
 * ========================================================================
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */

/* jshint latedef: false */

+function ($) {
  'use strict';

  // COLLAPSE PUBLIC CLASS DEFINITION
  // ================================

  var Collapse = function (element, options) {
    this.$element      = $(element)
    this.options       = $.extend({}, Collapse.DEFAULTS, options)
    this.$trigger      = $('[data-toggle="collapse"][href="#' + element.id + '"],' +
                           '[data-toggle="collapse"][data-target="#' + element.id + '"]')
    this.transitioning = null

    if (this.options.parent) {
      this.$parent = this.getParent()
    } else {
      this.addAriaAndCollapsedClass(this.$element, this.$trigger)
    }

    if (this.options.toggle) this.toggle()
  }

  Collapse.VERSION  = '3.3.7'

  Collapse.TRANSITION_DURATION = 350

  Collapse.DEFAULTS = {
    toggle: true
  }

  Collapse.prototype.dimension = function () {
    var hasWidth = this.$element.hasClass('width')
    return hasWidth ? 'width' : 'height'
  }

  Collapse.prototype.show = function () {
    if (this.transitioning || this.$element.hasClass('in')) return

    var activesData
    var actives = this.$parent && this.$parent.children('.panel').children('.in, .collapsing')

    if (actives && actives.length) {
      activesData = actives.data('bs.collapse')
      if (activesData && activesData.transitioning) return
    }

    var startEvent = $.Event('show.bs.collapse')
    this.$element.trigger(startEvent)
    if (startEvent.isDefaultPrevented()) return

    if (actives && actives.length) {
      Plugin.call(actives, 'hide')
      activesData || actives.data('bs.collapse', null)
    }

    var dimension = this.dimension()

    this.$element
      .removeClass('collapse')
      .addClass('collapsing')[dimension](0)
      .attr('aria-expanded', true)

    this.$trigger
      .removeClass('collapsed')
      .attr('aria-expanded', true)

    this.transitioning = 1

    var complete = function () {
      this.$element
        .removeClass('collapsing')
        .addClass('collapse in')[dimension]('')
      this.transitioning = 0
      this.$element
        .trigger('shown.bs.collapse')
    }

    if (!$.support.transition) return complete.call(this)

    var scrollSize = $.camelCase(['scroll', dimension].join('-'))

    this.$element
      .one('bsTransitionEnd', $.proxy(complete, this))
      .emulateTransitionEnd(Collapse.TRANSITION_DURATION)[dimension](this.$element[0][scrollSize])
  }

  Collapse.prototype.hide = function () {
    if (this.transitioning || !this.$element.hasClass('in')) return

    var startEvent = $.Event('hide.bs.collapse')
    this.$element.trigger(startEvent)
    if (startEvent.isDefaultPrevented()) return

    var dimension = this.dimension()

    this.$element[dimension](this.$element[dimension]())[0].offsetHeight

    this.$element
      .addClass('collapsing')
      .removeClass('collapse in')
      .attr('aria-expanded', false)

    this.$trigger
      .addClass('collapsed')
      .attr('aria-expanded', false)

    this.transitioning = 1

    var complete = function () {
      this.transitioning = 0
      this.$element
        .removeClass('collapsing')
        .addClass('collapse')
        .trigger('hidden.bs.collapse')
    }

    if (!$.support.transition) return complete.call(this)

    this.$element
      [dimension](0)
      .one('bsTransitionEnd', $.proxy(complete, this))
      .emulateTransitionEnd(Collapse.TRANSITION_DURATION)
  }

  Collapse.prototype.toggle = function () {
    this[this.$element.hasClass('in') ? 'hide' : 'show']()
  }

  Collapse.prototype.getParent = function () {
    return $(this.options.parent)
      .find('[data-toggle="collapse"][data-parent="' + this.options.parent + '"]')
      .each($.proxy(function (i, element) {
        var $element = $(element)
        this.addAriaAndCollapsedClass(getTargetFromTrigger($element), $element)
      }, this))
      .end()
  }

  Collapse.prototype.addAriaAndCollapsedClass = function ($element, $trigger) {
    var isOpen = $element.hasClass('in')

    $element.attr('aria-expanded', isOpen)
    $trigger
      .toggleClass('collapsed', !isOpen)
      .attr('aria-expanded', isOpen)
  }

  function getTargetFromTrigger($trigger) {
    var href
    var target = $trigger.attr('data-target')
      || (href = $trigger.attr('href')) && href.replace(/.*(?=#[^\s]+$)/, '') // strip for ie7

    return $(target)
  }


  // COLLAPSE PLUGIN DEFINITION
  // ==========================

  function Plugin(option) {
    return this.each(function () {
      var $this   = $(this)
      var data    = $this.data('bs.collapse')
      var options = $.extend({}, Collapse.DEFAULTS, $this.data(), typeof option == 'object' && option)

      if (!data && options.toggle && /show|hide/.test(option)) options.toggle = false
      if (!data) $this.data('bs.collapse', (data = new Collapse(this, options)))
      if (typeof option == 'string') data[option]()
    })
  }

  var old = $.fn.collapse

  $.fn.collapse             = Plugin
  $.fn.collapse.Constructor = Collapse


  // COLLAPSE NO CONFLICT
  // ====================

  $.fn.collapse.noConflict = function () {
    $.fn.collapse = old
    return this
  }


  // COLLAPSE DATA-API
  // =================

  $(document).on('click.bs.collapse.data-api', '[data-toggle="collapse"]', function (e) {
    var $this   = $(this)

    if (!$this.attr('data-target')) e.preventDefault()

    var $target = getTargetFromTrigger($this)
    var data    = $target.data('bs.collapse')
    var option  = data ? 'toggle' : $this.data()

    Plugin.call($target, option)
  })

}(jQuery);
</script>
<script>
window.initializeCodeFolding = function(show) {

  // handlers for show-all and hide all
  $("#rmd-show-all-code").click(function() {
    $('div.r-code-collapse').each(function() {
      $(this).collapse('show');
    });
  });
  $("#rmd-hide-all-code").click(function() {
    $('div.r-code-collapse').each(function() {
      $(this).collapse('hide');
    });
  });

  // index for unique code element ids
  var currentIndex = 1;

  // select all R code blocks
  var rCodeBlocks = $('pre.sourceCode, pre.r, pre.python, pre.bash, pre.sql, pre.cpp, pre.stan');
  rCodeBlocks.each(function() {

    // create a collapsable div to wrap the code in
    var div = $('<div class="collapse r-code-collapse"></div>');
    if (show)
      div.addClass('in');
    var id = 'rcode-643E0F36' + currentIndex++;
    div.attr('id', id);
    $(this).before(div);
    $(this).detach().appendTo(div);

    // add a show code button right above
    var showCodeText = $('<span>' + (show ? 'Hide' : 'Code') + '</span>');
    var showCodeButton = $('<button type="button" class="btn btn-default btn-xs code-folding-btn pull-right"></button>');
    showCodeButton.append(showCodeText);
    showCodeButton
        .attr('data-toggle', 'collapse')
        .attr('data-target', '#' + id)
        .attr('aria-expanded', show)
        .attr('aria-controls', id);

    var buttonRow = $('<div class="row"></div>');
    var buttonCol = $('<div class="col-md-12"></div>');

    buttonCol.append(showCodeButton);
    buttonRow.append(buttonCol);

    div.before(buttonRow);

    // update state of button on show/hide
    div.on('hidden.bs.collapse', function () {
      showCodeText.text('Code');
    });
    div.on('show.bs.collapse', function () {
      showCodeText.text('Hide');
    });
  });

}
</script>
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
.row { display: flex; }
.collapse { display: none; }
.in { display:block }
</style>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "hide");
});
</script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path=""><a href="#prefacio"><i class="fa fa-check"></i>Prefácio</a></li>
<li class="chapter" data-level="1" data-path=""><a href="#ch1_intro"><i class="fa fa-check"></i><b>1</b> Introdução aos Bancos de Dados</a><ul>
<li class="chapter" data-level="1.1" data-path=""><a href="#basicExampleOfStentsAndStrokes"><i class="fa fa-check"></i><b>1.1</b> Estudo de caso: usando <em>stents</em> para evitar derrames</a></li>
<li class="chapter" data-level="1.2" data-path=""><a href="#nocoes-basicas-de-dados"><i class="fa fa-check"></i><b>1.2</b> Noções básicas de dados</a><ul>
<li class="chapter" data-level="1.2.1" data-path=""><a href="#observacoes-variaveis-e-matrizes-de-dados"><i class="fa fa-check"></i><b>1.2.1</b> Observações, variáveis e matrizes de dados</a></li>
<li class="chapter" data-level="1.2.2" data-path=""><a href="#tipos-de-variaveis"><i class="fa fa-check"></i><b>1.2.2</b> Tipos de variáveis</a></li>
<li class="chapter" data-level="1.2.3" data-path=""><a href="#variableRelations"><i class="fa fa-check"></i><b>1.2.3</b> Relações entre variáveis</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path=""><a href="#overviewOfDataCollectionPrinciples"><i class="fa fa-check"></i><b>1.3</b> Visão geral dos princípios de coleta de dados</a><ul>
<li class="chapter" data-level="1.3.1" data-path=""><a href="#populationsAndSamples"><i class="fa fa-check"></i><b>1.3.1</b> Populações e amostras</a></li>
<li class="chapter" data-level="1.3.2" data-path=""><a href="#anecdotalEvidenceSubsection"><i class="fa fa-check"></i><b>1.3.2</b> Evidência anedótica</a></li>
<li class="chapter" data-level="1.3.3" data-path=""><a href="#amostragem-de-uma-populacao"><i class="fa fa-check"></i><b>1.3.3</b> Amostragem de uma população</a></li>
<li class="chapter" data-level="1.3.4" data-path=""><a href="#explanatoryAndResponse"><i class="fa fa-check"></i><b>1.3.4</b> Variáveis explicativas e de resposta</a></li>
<li class="chapter" data-level="1.3.5" data-path=""><a href="#introduzindo-estudos-observacionais-e-experimentos"><i class="fa fa-check"></i><b>1.3.5</b> Introduzindo estudos observacionais e experimentos</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path=""><a href="#estudos-observacionais-e-estrategias-de-amostragem"><i class="fa fa-check"></i><b>1.4</b> Estudos observacionais e estratégias de amostragem</a><ul>
<li class="chapter" data-level="1.4.1" data-path=""><a href="#estudos-observacionais"><i class="fa fa-check"></i><b>1.4.1</b> Estudos observacionais</a></li>
<li class="chapter" data-level="1.4.2" data-path=""><a href="#fourSamplingMethods"><i class="fa fa-check"></i><b>1.4.2</b> Quatro métodos de amostragem (tópico especial)</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path=""><a href="#experimentsSection"><i class="fa fa-check"></i><b>1.5</b> Experimentos</a></li>
<li class="chapter" data-level="1.6" data-path=""><a href="#experimentalDesignPrinciples"><i class="fa fa-check"></i><b>1.6</b> $ Princípios do design experimental</a><ul>
<li class="chapter" data-level="1.6.1" data-path=""><a href="#biasInHumanExperiments"><i class="fa fa-check"></i><b>1.6.1</b> Redução do viés em experimentos em humanos</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path=""><a href="#numericalData"><i class="fa fa-check"></i><b>1.7</b> Examinando dados numéricos</a><ul>
<li class="chapter" data-level="1.7.1" data-path=""><a href="#scatterPlots"><i class="fa fa-check"></i><b>1.7.1</b> Gráficos de dispersão para dados pareados</a></li>
<li class="chapter" data-level="1.7.2" data-path=""><a href="#dotPlot"><i class="fa fa-check"></i><b>1.7.2</b> Gráfico de pontos e a média</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<!--bookdown:title:end-->
<!--bookdown:title:start-->
<div class="figure">
<img src="imagem_site_disciplina.png" />

</div>
<div id="prefacio" class="section level1 unnumbered">
<h1>Prefácio</h1>
<div class="figure">
<img src="before_site_disciplina.png" />

</div>
</div>
<div id="ch1_intro" class="section level1">
<h1><span class="header-section-number">1</span> Introdução aos Bancos de Dados</h1>
<p>Os cientistas procuram responder a perguntas usando métodos rigorosos e observações cuidadosas. Essas observações – coletadas a partir de notas de campo, pesquisas e experimentos – formam a espinha dorsal de uma investigação estatística e são chamadas de <strong>banco de dados</strong>. Estatística é o estudo de como melhor coletar, analisar e tirar conclusões dos dados. É útil colocar estatísticas no contexto de um processo geral de investigação:</p>
<ul>
<li><p>Identifique uma questão ou problema.</p></li>
<li><p>Coletar dados relevantes sobre o tópico.</p></li>
<li><p>Analise os dados.</p></li>
<li><p>Faça uma conclusão.</p></li>
</ul>
<p>Estatística como um assunto se concentra em tornar os estágios 2-4 objetivos, rigorosos e eficientes. Isto é, a estatística tem três componentes principais: como melhor podemos coletar dados? Como deve ser analisado? E o que podemos inferir da análise? Os tópicos que os cientistas investigam são tão diversos quanto as perguntas que fazem. No entanto, muitas dessas investigações podem ser abordadas com um pequeno número de técnicas de coleta de dados, ferramentas analíticas e conceitos fundamentais em inferência estatística. Este capítulo fornece um vislumbre desses e de outros temas que encontraremos ao longo do restante do livro. Apresentamos os princípios básicos de cada ramo e aprendemos algumas ferramentas ao longo do caminho. Nós vamos encontrar aplicações de outros campos, alguns dos quais não são tipicamente associados à ciência, mas, mesmo assim, podem se beneficiar do estudo estatístico.</p>
<div id="basicExampleOfStentsAndStrokes" class="section level2">
<h2><span class="header-section-number">1.1</span> Estudo de caso: usando <em>stents</em> para evitar derrames</h2>
<p>Seção <a href="#basicExampleOfStentsAndStrokes">1.1</a> introduz um desafio clássico na estatística: avaliar a eficácia de um tratamento médico. Os termos nesta seção e, na verdade, em grande parte deste capítulo, serão revisitados posteriormente no texto. O plano, por enquanto, é simplesmente ter uma noção do papel que as estatísticas podem desempenhar na prática.</p>
<p>Nesta seção, vamos considerar um experimento que estuda a eficácia dos <em>stents</em> no tratamento de pacientes com risco de acidente vascular cerebral<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a>. Os <em>stents</em> são dispositivos colocados dentro dos vasos sanguíneos que auxiliam na recuperação do paciente após eventos cardíacos e reduzem o risco de um novo acidente ou morte. Muitos médicos esperavam que houvesse benefícios similares para pacientes com risco de derrame. Começamos escrevendo a pergunta principal que os pesquisadores esperam responder:</p>
<blockquote>
<p>O uso de <em>stents</em> reduz o risco de acidente vascular cerebral?</p>
</blockquote>
<p>Os pesquisadores que fizeram essa pergunta coletaram dados de 451 pacientes em risco. Cada paciente voluntário foi aleatoriamente designado para um dos dois grupos:</p>
<ul>
<li><p><strong>Grupo de tratamento</strong>: Os pacientes do grupo de tratamento receberam <em>stent</em> e tratamento médico. O manejo médico incluiu medicamentos, gerenciamento de fatores de risco e ajuda na modificação do estilo de vida.</p></li>
<li><p><strong>Grupo de controle</strong>: Os pacientes do grupo controle receberam o mesmo tratamento médico do grupo de tratamento, mas não receberam <em>stents</em>.</p></li>
</ul>
<p>Os pesquisadores distribuíram aleatoriamente 224 pacientes para o grupo de tratamento e 227 para o grupo de controle. Neste estudo, o grupo controle fornece um ponto de referência contra o qual podemos medir o impacto médico dos <em>stents</em> no grupo de tratamento.</p>
<p>Os pesquisadores estudaram o efeito dos <em>stents</em> em dois momentos: 30 dias após a inscrição e 365 dias após a inscrição. Os resultados de 5 pacientes estão resumidos na Tabela <a href="#tab:stentStudyResultsDF">1.1</a>. Os resultados dos pacientes são registrados como “acidente vascular cerebral” ou “nenhum evento”, representando se o paciente teve ou não um acidente vascular cerebral no final de um período de tempo.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">table1 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Paciente =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">450</span>, <span class="dv">451</span>), <span class="dt">Grupo =</span> <span class="kw">c</span>(<span class="st">&#39;tratamento&#39;</span>,                                                <span class="st">&#39;tratamento&#39;</span>,<span class="st">&#39;tratamento&#39;</span>,<span class="st">&#39;controle&#39;</span>,<span class="st">&#39;controle&#39;</span>),
                     <span class="dt">trinta_dias =</span> <span class="kw">c</span>(<span class="st">&#39;sem evento&#39;</span>,<span class="st">&#39;acidente&#39;</span>,<span class="st">&#39;sem evento&#39;</span>,<span class="st">&#39;sem evento&#39;</span>,
                                <span class="st">&#39;sem evento&#39;</span>),
                     <span class="dt">trezentos_sessenta_cinco_dias =</span> <span class="kw">c</span>(<span class="st">&#39;sem evento&#39;</span>,
                                                       <span class="st">&#39;acidente&#39;</span>,<span class="st">&#39;sem evento&#39;</span>,
                                                       <span class="st">&#39;sem evento&#39;</span>,<span class="st">&#39;sem evento&#39;</span>))

<span class="kw">colnames</span>(table1) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;Paciente&#39;</span>,<span class="st">&#39;Grupo&#39;</span>,<span class="st">&#39;0-30 dias&#39;</span>,<span class="st">&#39;0-365 dias&#39;</span>)

knitr<span class="op">::</span><span class="kw">kable</span>(table1, <span class="dt">caption =</span> <span class="st">&#39; Resultados para cinco pacientes do estudo stent&#39;</span>,
             <span class="dt">align =</span> <span class="st">&#39;c&#39;</span>)</code></pre></div>
<table>
<caption><span id="tab:stentStudyResultsDF">Tabela 1.1: </span> Resultados para cinco pacientes do estudo stent</caption>
<thead>
<tr class="header">
<th align="center">Paciente</th>
<th align="center">Grupo</th>
<th align="center">0-30 dias</th>
<th align="center">0-365 dias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">tratamento</td>
<td align="center">sem evento</td>
<td align="center">sem evento</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">tratamento</td>
<td align="center">acidente</td>
<td align="center">acidente</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">tratamento</td>
<td align="center">sem evento</td>
<td align="center">sem evento</td>
</tr>
<tr class="even">
<td align="center">450</td>
<td align="center">controle</td>
<td align="center">sem evento</td>
<td align="center">sem evento</td>
</tr>
<tr class="odd">
<td align="center">451</td>
<td align="center">controle</td>
<td align="center">sem evento</td>
<td align="center">sem evento</td>
</tr>
</tbody>
</table>
<p>Considerar os dados de cada paciente individualmente seria um caminho longo e complicado para responder à pergunta de pesquisa original. Em vez disso, executar uma análise estatística de dados nos permite considerar todos os dados de uma só vez. A Tabela <a href="#tab:stentStudyResults">1.2</a> resume os dados brutos de uma maneira mais útil. Nesta tabela, podemos ver rapidamente o que aconteceu durante todo o estudo. Por exemplo, para identificar o número de pacientes no grupo de tratamento que tiveram um derrame dentro de 30 dias, olhamos no lado esquerdo da mesa na intersecção do tratamento com o derrame: 33.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">table2 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="kw">rbind</span>(<span class="kw">c</span>(<span class="dv">33</span>, <span class="dv">191</span>, <span class="dv">45</span>, <span class="dv">179</span>), 
                           <span class="kw">c</span>(<span class="dv">13</span>, <span class="dv">214</span>, <span class="dv">28</span>, <span class="dv">199</span>), 
                           <span class="kw">c</span>(<span class="dv">46</span>, <span class="dv">405</span>, <span class="dv">73</span>, <span class="dv">378</span>)))

<span class="co">#organiza~ção dos nomes</span>
<span class="kw">rownames</span>(table2) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;tratamento&#39;</span>, <span class="st">&#39;controle&#39;</span>,<span class="st">&#39;total&#39;</span>)
<span class="kw">colnames</span>(table2) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;ataque cardíaco (0-30 dias)&#39;</span>, <span class="st">&#39;sem evento (0-30 dias)&#39;</span>,
                      <span class="st">&#39;ataque cardíaco (0-365 dias)&#39;</span>, <span class="st">&#39;sem evento (0-365 dias)&#39;</span>)

knitr<span class="op">::</span><span class="kw">kable</span>(table2, <span class="dt">align =</span> <span class="st">&#39;c&#39;</span>,
             <span class="dt">caption =</span> <span class="st">&#39;Estatística descritiva para o estudo sobre stent&#39;</span>)</code></pre></div>
<table>
<caption><span id="tab:stentStudyResults">Tabela 1.2: </span>Estatística descritiva para o estudo sobre stent</caption>
<thead>
<tr class="header">
<th></th>
<th align="center">ataque cardíaco (0-30 dias)</th>
<th align="center">sem evento (0-30 dias)</th>
<th align="center">ataque cardíaco (0-365 dias)</th>
<th align="center">sem evento (0-365 dias)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>tratamento</td>
<td align="center">33</td>
<td align="center">191</td>
<td align="center">45</td>
<td align="center">179</td>
</tr>
<tr class="even">
<td>controle</td>
<td align="center">13</td>
<td align="center">214</td>
<td align="center">28</td>
<td align="center">199</td>
</tr>
<tr class="odd">
<td>total</td>
<td align="center">46</td>
<td align="center">405</td>
<td align="center">73</td>
<td align="center">378</td>
</tr>
</tbody>
</table>

<div class="exercise">
<span id="exr:unnamed-chunk-2" class="exercise"><strong>Prática Orientada 1.1  </strong></span>Dos 224 pacientes do grupo de tratamento, 45 tiveram um derrame no final do primeiro ano. Usando esses dois números, calcule a proporção de pacientes no grupo de tratamento que teve um acidente vascular cerebral até o final do primeiro ano. (Por favor, note: as respostas para todos os exercícios de <strong>Práticas Orientadas</strong> são fornecidas usando notas de rodapé.)<a href="#fn2" class="footnoteRef" id="fnref2"><sup>2</sup></a>
</div>

<p>Podemos calcular estatísticas através da tabela. Uma <strong>estatística</strong> é um único número que resume uma grande quantidade de dados.<a href="#fn3" class="footnoteRef" id="fnref3"><sup>3</sup></a> Por exemplo, os principais resultados do estudo após um ano podem ser descritos por duas estatísticas resumidas: a proporção de pessoas que tiveram um derrame nos grupos de tratamento e de controle.</p>
<ul>
<li><p>Proporção que teve um derrame no grupo tratamento (<em>stent</em>): <span class="math display">\[\frac{45}{224} = 0.20 = 20\%\]</span></p></li>
<li><p>Proporção que teve um derrame no grupo de controle: <span class="math display">\[\frac{28}{227} = 0.12 = 12\%\]</span></p></li>
</ul>
<p>Estas duas estatísticas resumidas são úteis para procurar diferenças nos grupos, e temos uma surpresa: mais 8% de pacientes no grupo de tratamento tiveram um derrame! Isto é importante por duas razões. Primeiro, é contrário ao que os médicos esperavam, que os <em>stents</em> <em>reduziriam</em> a taxa de derrames. Segundo, leva a uma questão estatística: os dados mostram uma diferença “real” entre os grupos?</p>
<p>Essa segunda questão é sutil. Suponha que você jogue uma moeda 100 vezes. Embora a chance de uma moeda cair cara em uma dada moeda seja de 50%, provavelmente não observaremos exatamente 50 caras. Esse tipo de flutuação faz parte de praticamente qualquer tipo de processo de geração de dados. É possível que a diferença de 8% no estudo do <em>stent</em> se deva a essa variação natural. No entanto, quanto maior a diferença que observamos (para um tamanho de amostra específico), menos crível é que a diferença seja devida ao acaso. Então, o que estamos realmente perguntando é o seguinte: <strong>a diferença é tão grande que devemos rejeitar a noção de que isso se deve ao acaso?</strong></p>
<p>Embora ainda não tenhamos nossas ferramentas estatísticas para resolver totalmente essa questão por conta própria, podemos compreender as conclusões da análise publicada: havia evidências convincentes de danos por <em>stents</em> neste estudo de pacientes com AVC.</p>
<p><strong>Seja cuidadoso:</strong> não generalizamos os resultados deste estudo para todos os pacientes e todos os <em>stents</em>. Este estudo analisou pacientes com características muito específicas que se voluntariaram para fazer parte deste estudo e que podem não ser representativos de todos os pacientes com AVC. Além disso, existem muitos tipos de <em>stents</em> e este estudo considerou apenas o <em>stent Wingspan</em> auto-expansível (Boston Scientific). No entanto, este estudo nos deixa uma lição importante: devemos manter nossos olhos abertos para surpresas.</p>
</div>
<div id="nocoes-basicas-de-dados" class="section level2">
<h2><span class="header-section-number">1.2</span> Noções básicas de dados</h2>
<p>Apresentação eficaz e descrição dos dados é um primeiro passo na maioria das análises. Esta seção apresenta uma estrutura para organizar dados, bem como alguma terminologia que será usada ao longo deste livro.</p>
<div id="observacoes-variaveis-e-matrizes-de-dados" class="section level3">
<h3><span class="header-section-number">1.2.1</span> Observações, variáveis e matrizes de dados</h3>
<p>A Tabela <a href="#tab:email50DF">1.3</a> exibe as linhas 1, 2, 3 e 50 de um conjunto de dados referentes a 50 e-mails recebidos durante o início de 2012. Essas observações serão chamadas de conjunto de dados <code>email50</code> e são uma amostra aleatória de um conjunto de dados maior vamos ver na Seção <a href="#categoricalData"><strong>??</strong></a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(openintro)
<span class="kw">data</span>(<span class="st">&quot;email50&quot;</span>)

table3 &lt;-<span class="st"> </span>email50[,<span class="kw">c</span>(<span class="st">&#39;spam&#39;</span>, <span class="st">&#39;num_char&#39;</span>, <span class="st">&#39;line_breaks&#39;</span>, <span class="st">&#39;format&#39;</span>, <span class="st">&#39;number&#39;</span>)]
table3<span class="op">$</span>spam &lt;-<span class="st"> </span><span class="kw">ifelse</span>(table3<span class="op">$</span>spam  <span class="op">==</span><span class="st"> &#39;0&#39;</span>, <span class="st">&#39;não&#39;</span>, <span class="st">&#39;sim&#39;</span>)
table3<span class="op">$</span>format &lt;-<span class="st"> </span><span class="kw">ifelse</span>(table3<span class="op">$</span>format  <span class="op">==</span><span class="st"> &#39;0&#39;</span>, <span class="st">&#39;text&#39;</span>, <span class="st">&#39;html&#39;</span>)


knitr<span class="op">::</span><span class="kw">kable</span>(table3[<span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>,<span class="dv">50</span>),], <span class="dt">align =</span> <span class="st">&#39;c&#39;</span>,
             <span class="dt">caption =</span> <span class="st">&#39;Quatro linhas da matriz de dados email50.&#39;</span>)</code></pre></div>
<table>
<caption><span id="tab:email50DF">Tabela 1.3: </span>Quatro linhas da matriz de dados email50.</caption>
<thead>
<tr class="header">
<th></th>
<th align="center">spam</th>
<th align="center">num_char</th>
<th align="center">line_breaks</th>
<th align="center">format</th>
<th align="center">number</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td align="center">não</td>
<td align="center">21.705</td>
<td align="center">551</td>
<td align="center">html</td>
<td align="center">small</td>
</tr>
<tr class="even">
<td>2</td>
<td align="center">não</td>
<td align="center">7.011</td>
<td align="center">183</td>
<td align="center">html</td>
<td align="center">big</td>
</tr>
<tr class="odd">
<td>3</td>
<td align="center">sim</td>
<td align="center">0.631</td>
<td align="center">28</td>
<td align="center">text</td>
<td align="center">none</td>
</tr>
<tr class="even">
<td>50</td>
<td align="center">não</td>
<td align="center">15.829</td>
<td align="center">242</td>
<td align="center">html</td>
<td align="center">small</td>
</tr>
</tbody>
</table>
<p>Cada linha na tabela representa um único e-mail ou <strong>caso</strong>.<a href="#fn4" class="footnoteRef" id="fnref4"><sup>4</sup></a> As colunas representam características, chamadas <strong>variéveis</strong>, para cada um dos e-mails. Por exemplo, a primeira linha representa o email 1, que não é spam, contém 21,705 caracteres, 551 quebras de linha, está escrito em formato <em>HTML</em> e contém apenas números pequenos.</p>
<p>Na prática, é especialmente importante fazer perguntas esclarecedoras para garantir que aspectos importantes dos dados sejam compreendidos. Por exemplo, é sempre importante ter certeza de que sabemos o que cada variável significa e as unidades de medida. As descrições de todas as cinco variáveis de e-mail são dadas na Tabela <a href="#tab:email50Variables">1.4</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">table4 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">variavel =</span> <span class="kw">colnames</span>(table3),
                     <span class="dt">descricao =</span> <span class="kw">c</span>(<span class="st">&#39;Especifica se a mensagem eras spam&#39;</span>,
                                   <span class="st">&#39;O número de caracteres no email&#39;</span>,
                                   <span class="st">&#39;O número de quebras de linha no email (não incluindo quebras por figura)&#39;</span>,
                                   <span class="st">&#39; Indica se o email continha formatação especial, como negrito, tabelas, ou links, o que indicaria que a mensagem está no formato HTML&#39;</span>,
                                   <span class="st">&#39;Indica se o email não tinha nenhum número, um pequeno número (menor que 1 milhão), ou um número grande&#39;</span>))

knitr<span class="op">::</span><span class="kw">kable</span>(table4, <span class="dt">align =</span> <span class="st">&#39;r&#39;</span>, 
             <span class="dt">caption =</span> <span class="st">&#39; Variáveis e suas descrições para o conjunto de dados email50&#39;</span>)</code></pre></div>
<table>
<caption><span id="tab:email50Variables">Tabela 1.4: </span> Variáveis e suas descrições para o conjunto de dados email50</caption>
<thead>
<tr class="header">
<th align="right">variavel</th>
<th align="right">descricao</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">spam</td>
<td align="right">Especifica se a mensagem eras spam</td>
</tr>
<tr class="even">
<td align="right">num_char</td>
<td align="right">O número de caracteres no email</td>
</tr>
<tr class="odd">
<td align="right">line_breaks</td>
<td align="right">O número de quebras de linha no email (não incluindo quebras por figura)</td>
</tr>
<tr class="even">
<td align="right">format</td>
<td align="right">Indica se o email continha formatação especial, como negrito, tabelas, ou links, o que indicaria que a mensagem está no formato HTML</td>
</tr>
<tr class="odd">
<td align="right">number</td>
<td align="right">Indica se o email não tinha nenhum número, um pequeno número (menor que 1 milhão), ou um número grande</td>
</tr>
</tbody>
</table>
<p>Os dados na Tabela <a href="#tab:email50DF">1.3</a> representam a <strong>matriz de dados</strong>, que é uma maneira comum de organizar dados. Cada linha de uma matriz de dados corresponde a um caso único e cada coluna corresponde a uma variável. Uma matriz de dados para o estudo de acidente vascular cerebral foi introduzida na Seção <a href="#basicExampleOfStentsAndStrokes">1.1</a> é mostrado na Tabela <a href="#tab:stentStudyResultsDF">1.1</a>, onde os casos eram pacientes e havia três variáveis registradas para cada paciente.</p>
<p>As matrizes de dados são uma maneira conveniente de registrar e armazenar dados. Se outro indivíduo ou caso for adicionado ao conjunto de dados, uma linha adicional poderá ser facilmente adicionada. Da mesma forma, outra coluna pode ser adicionada para uma nova variável.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-3" class="exercise"><strong>Prática Orientada 1.2  </strong></span>Consideramos um conjunto de dados publicamente disponível que resume informações sobre os 3.143 municípios nos Estados Unidos, e chamamos isso de conjunto de dados <code>condado</code>. Este conjunto de dados inclui informações sobre cada município: seu nome, o estado em que reside, sua população em 2000 e 2010, gastos federais per capita, taxa de pobreza e cinco características adicionais. Como esses dados podem ser organizados em uma matriz de dados? Lembrete: procure nas notas de rodapé as respostas para exercícios no texto.<a href="#fn5" class="footnoteRef" id="fnref5"><sup>5</sup></a>
</div>

<p>Sete colunas do conjunto de dados <code>município</code> são mostrados na Tabela <a href="#tab:countyDF">1.5</a>, e as variáveis estão resumidas na Tabela <a href="#tab:countyVariables">1.6</a>. Esses dados foram coletados no site do Censo dos EUA<a href="#fn6" class="footnoteRef" id="fnref6"><sup>6</sup></a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(county)

knitr<span class="op">::</span><span class="kw">kable</span>(<span class="kw">head</span>(county, <span class="dv">7</span>), <span class="dt">align =</span> <span class="st">&#39;c&#39;</span>, 
             <span class="dt">caption =</span> <span class="st">&#39;Sete linhas do conjunto de dados condado.&#39;</span>)</code></pre></div>
<table>
<caption><span id="tab:countyDF">Tabela 1.5: </span>Sete linhas do conjunto de dados condado.</caption>
<thead>
<tr class="header">
<th align="center">name</th>
<th align="center">state</th>
<th align="center">pop2000</th>
<th align="center">pop2010</th>
<th align="center">fed_spend</th>
<th align="center">poverty</th>
<th align="center">homeownership</th>
<th align="center">multiunit</th>
<th align="center">income</th>
<th align="center">med_income</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Autauga County</td>
<td align="center">Alabama</td>
<td align="center">43671</td>
<td align="center">54571</td>
<td align="center">6.068095</td>
<td align="center">10.6</td>
<td align="center">77.5</td>
<td align="center">7.2</td>
<td align="center">24568</td>
<td align="center">53255</td>
</tr>
<tr class="even">
<td align="center">Baldwin County</td>
<td align="center">Alabama</td>
<td align="center">140415</td>
<td align="center">182265</td>
<td align="center">6.139862</td>
<td align="center">12.2</td>
<td align="center">76.7</td>
<td align="center">22.6</td>
<td align="center">26469</td>
<td align="center">50147</td>
</tr>
<tr class="odd">
<td align="center">Barbour County</td>
<td align="center">Alabama</td>
<td align="center">29038</td>
<td align="center">27457</td>
<td align="center">8.752158</td>
<td align="center">25.0</td>
<td align="center">68.0</td>
<td align="center">11.1</td>
<td align="center">15875</td>
<td align="center">33219</td>
</tr>
<tr class="even">
<td align="center">Bibb County</td>
<td align="center">Alabama</td>
<td align="center">20826</td>
<td align="center">22915</td>
<td align="center">7.122016</td>
<td align="center">12.6</td>
<td align="center">82.9</td>
<td align="center">6.6</td>
<td align="center">19918</td>
<td align="center">41770</td>
</tr>
<tr class="odd">
<td align="center">Blount County</td>
<td align="center">Alabama</td>
<td align="center">51024</td>
<td align="center">57322</td>
<td align="center">5.130910</td>
<td align="center">13.4</td>
<td align="center">82.0</td>
<td align="center">3.7</td>
<td align="center">21070</td>
<td align="center">45549</td>
</tr>
<tr class="even">
<td align="center">Bullock County</td>
<td align="center">Alabama</td>
<td align="center">11714</td>
<td align="center">10914</td>
<td align="center">9.973062</td>
<td align="center">25.3</td>
<td align="center">76.9</td>
<td align="center">9.9</td>
<td align="center">20289</td>
<td align="center">31602</td>
</tr>
<tr class="odd">
<td align="center">Butler County</td>
<td align="center">Alabama</td>
<td align="center">21399</td>
<td align="center">20947</td>
<td align="center">9.311835</td>
<td align="center">25.0</td>
<td align="center">69.0</td>
<td align="center">13.7</td>
<td align="center">16916</td>
<td align="center">30659</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">table6 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">variavel =</span> <span class="kw">colnames</span>(county), 
                     <span class="dt">descricao =</span> <span class="kw">c</span>(<span class="st">&#39;Nome do condado&#39;</span>,
                                   <span class="st">&#39;Estado onde fica o condado (também incluso o distrito de Colúmbia)&#39;</span>,
                                   <span class="st">&#39;População em 2000&#39;</span>,
                                   <span class="st">&#39;População em 2010&#39;</span>,
                                   <span class="st">&#39;Gasto federal per capita&#39;</span>,
                                   <span class="st">&#39;Porcentagem da população na pobreza&#39;</span>,
                                   <span class="st">&#39;Porcentagem da população que vive em sua própria casa ou vive com o dono (e.g. crianças vivendo com pais que são donos da casa)&#39;</span>,
                                   <span class="st">&#39; Percentagem de unidades habitacionais que fazem parte de estruturas multi unidade (e.g. apartamentos)&#39;</span>,
                                   <span class="st">&#39;Renda per capita&#39;</span>,
                                   <span class="st">&#39;Renda por habitação mediana para o condado, onde a renda por habitação é igual a renda total de todos ocupantes com mais de 15 anos de idade&#39;</span>))

knitr<span class="op">::</span><span class="kw">kable</span>(table6, <span class="dt">align =</span> <span class="st">&#39;r&#39;</span>, 
              <span class="dt">caption =</span> <span class="st">&#39;Variáveis e suas descrições para o banco de dados condado.&#39;</span>)</code></pre></div>
<table>
<caption><span id="tab:countyVariables">Tabela 1.6: </span>Variáveis e suas descrições para o banco de dados condado.</caption>
<thead>
<tr class="header">
<th align="right">variavel</th>
<th align="right">descricao</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">name</td>
<td align="right">Nome do condado</td>
</tr>
<tr class="even">
<td align="right">state</td>
<td align="right">Estado onde fica o condado (também incluso o distrito de Colúmbia)</td>
</tr>
<tr class="odd">
<td align="right">pop2000</td>
<td align="right">População em 2000</td>
</tr>
<tr class="even">
<td align="right">pop2010</td>
<td align="right">População em 2010</td>
</tr>
<tr class="odd">
<td align="right">fed_spend</td>
<td align="right">Gasto federal per capita</td>
</tr>
<tr class="even">
<td align="right">poverty</td>
<td align="right">Porcentagem da população na pobreza</td>
</tr>
<tr class="odd">
<td align="right">homeownership</td>
<td align="right">Porcentagem da população que vive em sua própria casa ou vive com o dono (e.g. crianças vivendo com pais que são donos da casa)</td>
</tr>
<tr class="even">
<td align="right">multiunit</td>
<td align="right">Percentagem de unidades habitacionais que fazem parte de estruturas multi unidade (e.g. apartamentos)</td>
</tr>
<tr class="odd">
<td align="right">income</td>
<td align="right">Renda per capita</td>
</tr>
<tr class="even">
<td align="right">med_income</td>
<td align="right">Renda por habitação mediana para o condado, onde a renda por habitação é igual a renda total de todos ocupantes com mais de 15 anos de idade</td>
</tr>
</tbody>
</table>
</div>
<div id="tipos-de-variaveis" class="section level3">
<h3><span class="header-section-number">1.2.2</span> Tipos de variáveis</h3>
<p>Examine as variáveis <code>fed_spend</code>, <code>pop2010</code>, <code>state</code>, e <code>med_income</code> no conjunto de dados <code>condado</code>. Cada uma dessas variáveis é inerentemente diferente das outras três, mas muitas delas compartilham certas características.</p>
<p>Primeiro considere <code>fed_spend</code>, que é dito ser uma variável <strong>numérica</strong>, pois pode ter uma ampla gama de valores numéricos e é sensato adicionar, subtrair ou obter médias com esses valores. Por outro lado, não classificaríamos os códigos de área de telefone como numéricos, uma vez que sua média, soma e diferença não têm um significado claro.</p>
<p>A <code>pop2010</code> variável também é numérica, embora pareça ser um pouco diferente de <code>fed_spend</code>. Esta variável da contagem da população só pode ter números inteiros não negativos (<span class="math inline">\(1,2,3,\dots\)</span>). Por essa razão, a variável <em>população</em> é dita ser <strong>discreta</strong> já que só pode assumir valores numéricos com saltos. Por outro lado, diz-se que a variável gasto federal é <strong>contínua</strong>.</p>
<p>A variável <code>state</code> pode levar até 51 valores, contabilizando Washington, DC: AL,<span class="math inline">\(\dots\)</span>, e WY. Porque as próprias respostas são categorias, <code>state</code> é chamada uma variável <strong>categórica</strong>, e os valores possíveis são chamados de <em>níveis da variável</em>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">knitr<span class="op">::</span><span class="kw">include_graphics</span>(<span class="st">&quot;variables.png&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:variables"></span>
<img src="variables.png" alt="Repartição das variáveis em seus respectivos tipos." width="100%" height="30%" />
<p class="caption">
Figura 1.1: Repartição das variáveis em seus respectivos tipos.
</p>
</div>

<div class="example">
<span id="exm:unnamed-chunk-4" class="example"><strong>Exemplo 1.1  </strong></span>Os dados foram coletados sobre os alunos em um curso de estatística. Três variáveis foram registradas para cada aluno: número de irmãos, altura do aluno e se o aluno já havia feito um curso de estatística. Classifique cada uma das variáveis como numérica contínua, numérica discreta ou categórica.
</div>

<p>O número de irmãos e a altura dos alunos representam variáveis numéricas. Como o número de irmãos é uma contagem, ele é discreto. Altura varia continuamente, por isso é uma variável numérica contínua. A última variável classifica os alunos em duas categorias - aqueles que fizeram e aqueles que não fizeram um curso de estatística – o que torna essa variável categórica.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-5" class="exercise"><strong>Prática Orientada 1.3  </strong></span>Considere as variáveis <strong>grupo</strong> e <strong>resultado</strong> (a 30 dias) do estudo <em>stent</em> na Seção <a href="#basicExampleOfStentsAndStrokes">1.1</a>. São estas variáveis numéricas ou categóricas?<a href="#fn7" class="footnoteRef" id="fnref7"><sup>7</sup></a>
</div>

</div>
<div id="variableRelations" class="section level3">
<h3><span class="header-section-number">1.2.3</span> Relações entre variáveis</h3>
<p>Muitas análises são motivadas por um pesquisador que procura uma relação entre duas ou mais variáveis. Um cientista social pode gostar de responder a algumas das seguintes perguntas:</p>
<ul>
<li><p>Os gastos federais, em média, são maiores ou menores nos condados com altas taxas de pobreza?</p></li>
<li><p>Se a variável <em>casa própria</em> for menor que a média nacional em um município, a percentagem de estruturas de várias unidades naquele município provavelmente estará acima ou abaixo da média nacional?</p></li>
<li><p>Quais municípios têm uma renda média maior: aqueles que decretam uma ou mais proibições de fumar ou aqueles que não a decretaram?</p></li>
</ul>
<p>Para responder a essas perguntas, os dados devem ser coletados, como o conjunto de dados <code>condado</code> mostrado na Tabela <a href="#tab:countyDF">1.5</a>. Examinar as estatísticas-resumo poderia fornecer <em>insights</em> para cada uma das três perguntas sobre condados. Além disso, os gráficos podem ser usados para resumir visualmente os dados e são úteis para responder a essas perguntas também. <strong>Gráficos de dispersão</strong> são um tipo de gráfico usado para estudar a relação entre duas variáveis numéricas. A Figura <a href="#fig:countyfedspendVsPoverty">1.2</a> compara as variáveis <code>fed_spend</code> e <code>poverty</code>.</p>
<p>Cada ponto representa um único condado. Por exemplo, o ponto realçado corresponde ao Condado 1088 no conjunto de dados: Owsley County, Kentucky, que tinha uma taxa de pobreza de 41,5% e gastos federais de $21,50 per capita. O gráfico de dispersão sugere uma relação entre as duas variáveis: os municípios com alta taxa de pobreza também tendem a ter um pouco mais de gastos federais. Podemos pensar em por que essa relação existe e investigar cada ideia para determinar qual é a explicação mais razoável.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> county, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> poverty, <span class="dt">y =</span> fed_spend)) <span class="op">+</span><span class="st">  </span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.border =</span> <span class="kw">element_rect</span>(<span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="ot">NA</span>, <span class="dt">size =</span> <span class="dv">1</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;Pobreza&#39;</span>, <span class="dt">y =</span> <span class="st">&#39;Gasto federal per capita&#39;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ylim</span>(<span class="dv">0</span>, <span class="dv">30</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">50</span>, <span class="dv">10</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_segment</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="dv">0</span>, <span class="dt">y =</span> <span class="fl">21.5</span>, <span class="dt">xend =</span> <span class="fl">41.5</span>, <span class="dt">yend =</span> <span class="fl">21.5</span>), 
               <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_segment</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="fl">41.5</span>, <span class="dt">y =</span> <span class="dv">0</span>, <span class="dt">xend =</span> <span class="fl">41.5</span>, <span class="dt">yend =</span> <span class="fl">21.5</span>), 
               <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:countyfedspendVsPoverty"></span>
<img src="ch1_intro_files/figure-html/countyfedspendVsPoverty-1.png" alt="Um gráfico de dispersão mostrando fed_spend contra poverty." width="100%" height="30%" />
<p class="caption">
Figura 1.2: Um gráfico de dispersão mostrando fed_spend contra poverty.
</p>
</div>

<div class="exercise">
<span id="exr:unnamed-chunk-6" class="exercise"><strong>Prática Orientada 1.4  </strong></span>Examine as variáveis no banco de dados <code>email50</code>, descritos na Tabela <a href="#tab:email50Variables">1.4</a>. Crie duas perguntas sobre os relacionamentos entre essas variáveis que são de seu interesse.<a href="#fn8" class="footnoteRef" id="fnref8"><sup>8</sup></a>
</div>

<p>Diz-se que as duas variáveis estão associadas porque o gráfico mostra um padrão discernível. Quando duas variáveis mostram alguma conexão umas com as outras, elas são chamadas variáveis <strong>associadas</strong>. Variáveis associadas também podem ser chamadas variáveis <em>dependentes</em> e vice-versa.</p>

<div class="example">
<span id="exm:unnamed-chunk-7" class="example"><strong>Exemplo 1.2  </strong></span>Este exemplo examina a relação entre a proporção de casa própria e a porcentagem de unidades em estruturas de multi-unidades (por exemplo, apartamentos e condomínios), que é visualizada usando um gráfico de dispersão na Figura <a href="#fig:multiunitsVsOwnership">1.3</a>. Essas variáveis estão associadas?
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> countyComplete, 
       <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> housing_multi_unit, <span class="dt">y =</span> home_ownership)) <span class="op">+</span><span class="st">  </span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.border =</span> <span class="kw">element_rect</span>(<span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="ot">NA</span>, <span class="dt">size =</span> <span class="dv">1</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;Porcentagem de Unidades em Estruturas de Multi-Unidades&#39;</span>, 
       <span class="dt">y =</span> <span class="st">&#39;Proporção de Casa Própria&#39;) + </span>
<span class="st">  geom_point()</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:multiunitsVsOwnership"></span>
<img src="ch1_intro_files/figure-html/multiunitsVsOwnership-1.png" alt="Gráfico de dispersão entre a proporção de casa própria e a porcentagem de unidades eem estruturas de multi-unidades" width="100%" height="30%" />
<p class="caption">
Figura 1.3: Gráfico de dispersão entre a proporção de casa própria e a porcentagem de unidades eem estruturas de multi-unidades
</p>
</div>
<p>Parece que quanto maior a fração de unidades em estruturas com várias unidades, menor a taxa de casa própria. Como existe alguma relação entre as variáveis, elas estão associadas.</p>
<p>Porque há uma tendência de queda na Figura <a href="#fig:multiunitsVsOwnership">1.3</a> – municípios com mais unidades em estruturas de várias unidades estão associados a uma menor casa própria – essas variáveis são consideradas <strong>associadas negativamente</strong>. Uma <strong>associação positiva</strong> é mostrada na relação entre as variáveis <em>poverty</em> e <em>fed_spend</em> representadas na Figura <a href="#fig:countyfedspendVsPoverty">1.2</a>, onde os municípios com maiores taxas de pobreza tendem a receber mais gastos federais per capita. Se duas variáveis não estão associadas, então elas são <strong>independentes</strong>. Ou seja, duas variáveis são independentes se não houver relação evidente entre as duas.</p>
<div class="alert alert-info">
<p><strong>Associado ou independente, não ambos</strong>: Um par de variáveis estão relacionadas de alguma forma (associadas) ou não (independentes). Nenhum par de variáveis são associadas e independentes.</p>
</div>
</div>
</div>
<div id="overviewOfDataCollectionPrinciples" class="section level2">
<h2><span class="header-section-number">1.3</span> Visão geral dos princípios de coleta de dados</h2>
<p>O primeiro passo na condução de pesquisas é identificar tópicos ou questões que devem ser investigados. Uma pergunta de pesquisa claramente apresentada é útil para identificar quais assuntos ou casos devem ser estudados e quais variáveis são importantes. Também é importante considerar <em>como</em> os dados são coletados para que sejam confiáveis e ajudem a atingir as metas de pesquisa.</p>
<div id="populationsAndSamples" class="section level3">
<h3><span class="header-section-number">1.3.1</span> Populações e amostras</h3>
<p>Considere as três perguntas de pesquisa a seguir:</p>
<ul>
<li><p>Qual é o teor médio de mercúrio no peixe-espada do Oceano Atlântico?</p></li>
<li><p>Nos últimos 5 anos, qual é o tempo médio para concluir um curso para alunos de graduação da Duke?</p></li>
<li><p>Um novo medicamento reduz o número de mortes em pacientes com doença cardíaca grave?</p></li>
</ul>
<p>Cada questão de pesquisa refere-se a uma <strong>população alvo</strong>. Na primeira questão, a população alvo é todo o peixe-espada no oceano Atlântico, e cada peixe representa um caso. Muitas vezes, é muito caro coletar dados para todos os casos em uma população. Em vez disso, uma amostra é obtida. A <strong>amostra</strong> representa um subconjunto dos casos e geralmente é uma pequena fração da população. Por exemplo, 60 peixes-espada (ou algum outro número) na população podem ser selecionados, e esses dados de amostra podem ser usados para fornecer uma estimativa da média populacional e responder à pergunta da pesquisa.</p>

<div class="exercise">
<span id="exr:identifyingThePopulationForTwoQuestionsInPopAndSampSubsection" class="exercise"><strong>Prática Orientada 1.5  </strong></span>Para a segunda e terceira questões acima, identifique a população alvo e o que representa um caso individual.<a href="#fn9" class="footnoteRef" id="fnref9"><sup>9</sup></a>
</div>

</div>
<div id="anecdotalEvidenceSubsection" class="section level3">
<h3><span class="header-section-number">1.3.2</span> Evidência anedótica</h3>
<p>Considere as seguintes respostas possíveis para as três questões de pesquisa:</p>
<ul>
<li><p>Um homem no noticiário tem envenenamento por mercúrio por comer espadarte, então a concentração média de mercúrio em espadarte deve ser perigosamente alta.</p></li>
<li><p>Eu conheci dois alunos que levaram mais de sete anos para se formar na Duke, então deve levar mais tempo para se formar na Duke do que em muitas outras faculdades.</p></li>
<li><p>O pai da minha amiga teve um ataque cardíaco e morreu depois que eles lhe deram uma nova droga para doença cardíaca, então a droga não deve funcionar.</p></li>
</ul>
<p>Cada conclusão é baseada em dados. No entanto, existem dois problemas. Primeiro, os dados representam apenas um ou dois casos. Em segundo lugar, e mais importante, não está claro se esses casos são realmente representativos da população. Dados coletados dessa maneira casual são chamados <strong>evidência anedótica</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">knitr<span class="op">::</span><span class="kw">include_graphics</span>(<span class="st">&quot;mnWinter.jpg&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:mnWinter"></span>
<img src="mnWinter.JPG" alt="Em fevereiro de 2010, alguns especialistas da mídia citaram uma grande tempestade de neve como evidência válida contra o aquecimento global. Como o comediante Jon Stewart apontou: É uma tempestade, em uma região, de um país." width="100%" height="30%" />
<p class="caption">
Figura 1.4: Em fevereiro de 2010, alguns especialistas da mídia citaram uma grande tempestade de neve como evidência válida contra o aquecimento global. Como o comediante Jon Stewart apontou: É uma tempestade, em uma região, de um país.
</p>
</div>
<div class="alert alert-info">
<p><strong>Evidência anedótica</strong>: Tenha cuidado com os dados coletados de maneira aleatória. Tal evidência pode ser verdadeira e verificável, mas pode apenas representar casos extraordinários.</p>
</div>
<p>A evidência anedótica é tipicamente composta de casos incomuns que lembramos com base em suas características marcantes. Por exemplo, é mais provável que nos lembremos das duas pessoas que conhecemos que levaram sete anos para se formar do que as outras seis que se formaram em quatro anos. Em vez de olhar para os casos mais incomuns, devemos examinar uma amostra de muitos casos que representam a população.</p>
</div>
<div id="amostragem-de-uma-populacao" class="section level3">
<h3><span class="header-section-number">1.3.3</span> Amostragem de uma população</h3>
<p>Podemos tentar estimar o tempo para a graduação de alunos de graduação da Duke nos últimos 5 anos, coletando uma amostra de alunos. Todos os graduados nos últimos 5 anos representam a população, e graduados que são amostra. Em geral, procuramos sempre <strong>aleatoriamente</strong> selecionar uma amostra de uma população. O tipo mais básico de seleção aleatória é equivalente a como os sorteios são conduzidos. Por exemplo, na seleção de graduados, poderíamos escrever o nome de cada graduado em um bilhete de rifa e comprar 100 ingressos. Os nomes selecionados representariam uma amostra aleatória de 100 graduados.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">knitr<span class="op">::</span><span class="kw">include_graphics</span>(<span class="st">&quot;popToSampleGraduates.png&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:popToSampleGraduates"></span>
<img src="popToSampleGraduates.png" alt="Neste gráfico, cinco graduados são selecionados aleatoriamente da população para serem incluídos na amostra." width="80%" height="30%" />
<p class="caption">
Figura 1.5: Neste gráfico, cinco graduados são selecionados aleatoriamente da população para serem incluídos na amostra.
</p>
</div>
<p>Por que escolher uma amostra aleatoriamente? Por que não escolher apenas uma amostra à mão? Considere o seguinte cenário.</p>

<div class="example">
<span id="exm:unnamed-chunk-8" class="example"><strong>Exemplo 1.3  </strong></span>Suponha que perguntemos a um aluno que esteja se formando em nutrição para selecionar vários graduados para o estudo. Que tipo de alunos você acha que ela pode colecionar? Você acha que sua amostra seria representativa de todos os graduados?
</div>

<p>Talvez ela escolheria um número desproporcional de graduados em campos relacionados à saúde. Ou talvez a seleção dela fosse bem representativa da população. Ao selecionar amostras manualmente, corremos o risco de escolher uma amostra <strong>tendenciosa</strong>, mesmo que esse preconceito não seja intencional ou difícil de discernir.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">knitr<span class="op">::</span><span class="kw">include_graphics</span>(<span class="st">&#39;popToSubSampleGraduates.png&#39;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:popToSubSampleGraduates"></span>
<img src="popToSubSampleGraduates.png" alt="Em vez de amostragem de todos os graduados igualmente, um nutricionista pode, inadvertidamente, escolher graduados com cursos relacionados à saúde de forma desproporcional." width="80%" height="30%" />
<p class="caption">
Figura 1.6: Em vez de amostragem de todos os graduados igualmente, um nutricionista pode, inadvertidamente, escolher graduados com cursos relacionados à saúde de forma desproporcional.
</p>
</div>
<p>Se alguém tiver permissão para escolher exatamente quais graduados foram incluídos na amostra, é totalmente possível que a amostra possa ser distorcida aos interesses dessa pessoa, o que pode ser totalmente não intencional. Isso introduz um <em>viés</em> na amostra. Uma amostragem aleatória ajuda a resolver esse problema. A amostra aleatória mais básica é chamada de <strong>amostra aleatória simples</strong>, e é equivalente a usar um sorteio para selecionar casos. Isso significa que cada caso na população tem uma chance igual de ser incluído e não há conexão implícita entre os casos na amostra.</p>
<blockquote>
<p>Às vezes, uma amostra aleatória simples é difícil de implementar e um método alternativo é útil. Um método substituto é uma <strong>amostra sistemática</strong>, onde um caso é amostrado depois de deixar um número fixo de outros, digamos 10 outros casos, passar. Como essa abordagem usa um mecanismo que não é facilmente sujeito a vieses pessoais, geralmente produz uma amostra razoavelmente representativa. Este livro se concentrará em amostras aleatórias, já que o uso de amostras sistemáticas é incomum e requer considerações adicionais do contexto.</p>
</blockquote>
<p>O ato de pegar uma amostra aleatória simples ajuda a minimizar o viés. No entanto, o preconceito pode surgir de outras formas. Mesmo quando as pessoas são escolhidas aleatoriamente, por exemplo, deve-se ter cautela se a <em>não resposta</em> está alta. Por exemplo, se apenas 30% das pessoas amostradas aleatoriamente para uma pesquisa realmente responderem, então não está claro se os resultados são representativos de toda a população. Esse termo <strong>viés de não resposta</strong> pode distorcer resultados.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">knitr<span class="op">::</span><span class="kw">include_graphics</span>(<span class="st">&#39;surveySample.png&#39;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:surveySample"></span>
<img src="surveySample.png" alt="Devido à possibilidade de não resposta, os estudos de pesquisa só podem atingir um determinado grupo dentro da população. É difícil, e muitas vezes impossível, corrigir completamente esse problema." width="80%" height="30%" />
<p class="caption">
Figura 1.7: Devido à possibilidade de não resposta, os estudos de pesquisa só podem atingir um determinado grupo dentro da população. É difícil, e muitas vezes impossível, corrigir completamente esse problema.
</p>
</div>
<p>Outro método comum é uma <strong>amostra de conveniência</strong>, onde os indivíduos que são facilmente acessíveis têm maior probabilidade de serem incluídos na amostra. Por exemplo, se uma pesquisa política for feita em pessoas que andam no Bronx, isso não representará toda a cidade de Nova York. Muitas vezes é difícil discernir qual subpopulação uma amostra de conveniência representa.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-9" class="exercise"><strong>Prática Orientada 1.6  </strong></span>Podemos acessar facilmente classificações de produtos, vendedores e empresas por meio de sites. Essas classificações são baseadas apenas naquelas pessoas que fazem de tudo para fornecer uma classificação. Se 50% das avaliações on-line de um produto forem negativas, você acha que isso significa que 50% dos compradores estão insatisfeitos com o produto?<a href="#fn10" class="footnoteRef" id="fnref10"><sup>10</sup></a>
</div>

</div>
<div id="explanatoryAndResponse" class="section level3">
<h3><span class="header-section-number">1.3.4</span> Variáveis explicativas e de resposta</h3>
<p>Considere a pergunta que foi feita para o conjunto de dados <code>condado</code> na seção <a href="#variableRelations">1.2.3</a>:</p>
<ul>
<li>Os gastos federais, em média, são maiores ou menores nos condados com altas taxas de pobreza?</li>
</ul>
<p>Se suspeitarmos que a pobreza possa afetar os gastos em um país, então a pobreza é a variável <strong>explanatória</strong> e o gasto federal é a variável <strong>resposta</strong> no relacionamento.<a href="#fn11" class="footnoteRef" id="fnref11"><sup>11</sup></a></p>
<div class="alert alert-info">
<p><strong><strong>Dica</strong>: Variáveis explicativas e resposta</strong>: Para identificar a variável explicativa em um par de variáveis, identifique qual das duas é suspeita de afetar a outra e planeje uma análise apropriada.</p>
</div>
<div class="alert alert-info">
<p><strong><strong>Cuidado:</strong> associação não implica causalidade</strong>: Rotular variáveis como <em>explicativa</em> e <em>resposta</em> não garante que a relação entre os dois seja realmente causal, mesmo se houver uma associação identificada entre as duas variáveis. Usamos esses rótulos apenas para rastrear qual variável suspeitamos que afeta a outra.</p>
</div>
<p>Em alguns casos, não há variável explicativa ou resposta.</p>
<p>Considere a seguinte pergunta da seção <a href="#variableRelations">1.2.3</a>:</p>
<ul>
<li>Se a casa própria for menor que a média nacional em um município, a percentagem de estruturas de várias unidades naquele município provavelmente estará acima ou abaixo da média nacional?</li>
</ul>
<p>É difícil decidir qual dessas variáveis deve ser considerada a variável explicativa e resposta, ou seja, a direção é ambígua, portanto, nenhum rótulo explicativo ou de resposta é sugerido aqui.</p>
</div>
<div id="introduzindo-estudos-observacionais-e-experimentos" class="section level3">
<h3><span class="header-section-number">1.3.5</span> Introduzindo estudos observacionais e experimentos</h3>
<p>Existem dois tipos principais de coleta de dados: estudos observacionais e experimentos.</p>
<p>Pesquisadores realizam um <strong>estudo observacional</strong> quando coletam dados de uma maneira que não interfere diretamente na forma como os dados surgem. Por exemplo, os pesquisadores podem coletar informações por meio de pesquisas, revisar registros médicos ou da empresa ou seguir uma <em>coorte</em> de muitos indivíduos semelhantes para estudar por que certas doenças podem se desenvolver. Em cada uma dessas situações, os pesquisadores simplesmente observam os dados que surgem. Em geral, estudos observacionais podem fornecer evidências de uma associação natural entre variáveis, mas não podem, por si só, mostrar uma conexão causal.</p>
<p>Quando os pesquisadores querem investigar a possibilidade de uma conexão causal, eles conduzem um <strong>experimento</strong>. Geralmente, haverá uma variável explicativa e uma variável de resposta. Por exemplo, podemos suspeitar que administrar uma droga reduzirá a mortalidade em pacientes com ataque cardíaco no ano seguinte. Para verificar se existe realmente uma conexão causal entre a variável explicativa e a resposta, os pesquisadores coletarão uma amostra de indivíduos e os dividirão em grupos. Os indivíduos em cada grupo são atribuídos a um tratamento. Quando os indivíduos são aleatoriamente designados para um grupo, o experimento é chamado de <strong>experimento aleatório</strong>. Por exemplo, cada paciente com ataque cardíaco no estudo pode ser aleatoriamente designado, talvez jogando uma moeda, em um dos dois grupos: o primeiro grupo recebe um <em>placebo</em> e o segundo recebe o medicamento. Veja o estudo de caso na Seção <a href="#basicExampleOfStentsAndStrokes">1.1</a> para outro exemplo de um experimento, embora esse estudo não empregou um placebo.</p>
<div class="alert alert-info">
<p><strong>Associação <span class="math inline">\(\neq\)</span> causa</strong>: Em geral, a associação não implica causalidade, e a causalidade só pode ser inferida a partir de um experimento randomizado.</p>
</div>
</div>
</div>
<div id="estudos-observacionais-e-estrategias-de-amostragem" class="section level2">
<h2><span class="header-section-number">1.4</span> Estudos observacionais e estratégias de amostragem</h2>
<div id="estudos-observacionais" class="section level3">
<h3><span class="header-section-number">1.4.1</span> Estudos observacionais</h3>
<p>Geralmente, os dados em estudos observacionais são coletados apenas pelo monitoramento do que ocorre, enquanto os experimentos exigem que a variável explicativa primária em um estudo seja atribuída para cada sujeito pelos pesquisadores.</p>
<p>Fazer conclusões causais baseadas em experimentos é geralmente razoável. No entanto, fazer as mesmas conclusões causais com base em dados observacionais pode ser traiçoeiro e não é recomendado. Assim, estudos observacionais são geralmente suficientes apenas para mostrar associações.</p>

<div class="exercise">
<span id="exr:sunscreenLurkingExample" class="exercise"><strong>Prática Orientada 1.7  </strong></span>Suponha que um estudo observacional acompanhasse o uso de protetor solar e câncer de pele, e descobriu-se que quanto mais protetor solar alguém usava, maior a probabilidade de a pessoa ter câncer de pele. Isso significa que o protetor solar <strong>causa</strong> câncer de pele?<a href="#fn12" class="footnoteRef" id="fnref12"><sup>12</sup></a>
</div>

<p>Algumas pesquisas anteriores nos dizem que usar protetor solar realmente reduz o risco de câncer de pele, então talvez haja outra variável que pode explicar essa associação hipotética entre uso de filtro solar e câncer de pele. Uma informação importante que está ausente é a exposição ao sol. Se alguém está no sol o dia todo, ela é mais propensa a usar protetor solar e mais chances de ter câncer de pele. A exposição ao sol não é contabilizada na simples investigação.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">knitr<span class="op">::</span><span class="kw">include_graphics</span>(<span class="st">&#39;sunCausesCancer.png&#39;</span>)</code></pre></div>
<p><img src="sunCausesCancer.png" width="100%" height="30%" style="display: block; margin: auto;" /></p>
<p>A exposição ao sol é o que é chamado de <strong>variável de confusão</strong><a href="#fn13" class="footnoteRef" id="fnref13"><sup>13</sup></a>. Que é uma variável correlacionada com as variáveis explicativas e respostas. Enquanto um método para justificar a tomada de conclusões causais a partir de estudos observacionais é exaurir a busca por variáveis de confusão, não há garantia de que todas as variáveis confusas possam ser examinadas ou medidas.</p>
<p>Da mesma forma, o conjunto de dados <code>condado</code> é um estudo observacional com variáveis confundidoras, e seus dados não podem ser facilmente usados para fazer conclusões causais.</p>

<div class="exercise">
<p><span id="exr:unnamed-chunk-11" class="exercise"><strong>Prática Orientada 1.8  </strong></span>A Figura <a href="#fig:multiunitsVsOwnership">1.3</a> mostra uma associação negativa entre a taxa de propriedade e a porcentagem de estruturas de múltiplas unidades em um município. No entanto, não é razoável concluir que existe uma relação causal entre as duas variáveis. Sugira uma ou mais outras variáveis que possam explicar a relação visível na Figura <a href="#fig:multiunitsVsOwnership">1.3</a>.<a href="#fn14" class="footnoteRef" id="fnref14"><sup>14</sup></a></p>
</div>

<p>Estudos observacionais vêm em duas formas: estudos prospectivos e retrospectivos. Um <strong>estudo prospectivo</strong> identifica os indivíduos e coleta informações à medida que os eventos se desdobram. Por exemplo, pesquisadores médicos podem identificar e acompanhar um grupo de indivíduos semelhantes durante muitos anos para avaliar as possíveis influências do comportamento no risco de câncer. Um exemplo de tal estudo é <em>The Nurses ’Health Study</em>, iniciado em 1976 e expandido em 1989<a href="#fn15" class="footnoteRef" id="fnref15"><sup>15</sup></a>. Este estudo prospectivo recruta enfermeiros registrados e, em seguida, coleta dados deles usando questionários. <strong>Estudos retrospectivos</strong> coletam dados após os eventos terem ocorrido, por exemplo os pesquisadores podem revisar os eventos passados nos registros médicos. Alguns conjuntos de dados, como <code>condado</code>, podem conter variáveis coletadas prospectiva e retrospectivamente. Os governos locais coletam prospectivamente algumas variáveis à medida que os eventos se desenrolam (por exemplo, vendas de varejo) enquanto o governo federal coletou retrospectivamente outras durante o censo de 2010 (por exemplo, contagem da população do condado).</p>
</div>
<div id="fourSamplingMethods" class="section level3">
<h3><span class="header-section-number">1.4.2</span> Quatro métodos de amostragem (tópico especial)</h3>
<p>Quase todos os métodos estatísticos são baseados na noção de aleatoriedade implícita. Se os dados observacionais não forem coletados em uma estrutura aleatória de uma população, esses métodos estatísticos – as estimativas e os erros associados às estimativas – não são confiáveis. Aqui, consideramos quatro técnicas de amostragem aleatória: amostragem simples, estratificada, por conglomerados e de múltiplos estágios. Figuras <a href="#fig:simplestratified"><strong>??</strong></a> e @ref(fig:clustermultistage} fornecem representações gráficas dessas técnicas.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(COL)
<span class="kw">set.seed</span>(<span class="dv">4</span>)
N &lt;-<span class="st"> </span><span class="dv">108</span>
n &lt;-<span class="st"> </span><span class="dv">18</span>
colSamp &lt;-<span class="st"> </span>COL[<span class="dv">4</span>]
PCH &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">20</span>)[<span class="dv">3</span>], <span class="dv">3</span>)

col &lt;-<span class="st"> </span><span class="kw">rep</span>(COL[<span class="dv">1</span>], N)
pch &lt;-<span class="st"> </span>PCH[<span class="kw">match</span>(col, COL)]

<span class="kw">BuildSRS</span>()</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:simplestratified1"></span>
<img src="ch1_intro_files/figure-html/simplestratified-1.png" alt="Exemplos de amostragem simples  e amostragem estratificada. No painel superior, a amostragem aleatória simples foi usada para selecionar aleatoriamente os 18 casos. No painel inferior, utilizou-se amostragem estratificada: os casos foram agrupados em estratos e, em seguida, a amostragem aleatória simples foi feita para cada estrato." width="100%" height="100%" />
<p class="caption">
Figura 1.8: Exemplos de amostragem simples e amostragem estratificada. No painel superior, a amostragem aleatória simples foi usada para selecionar aleatoriamente os 18 casos. No painel inferior, utilizou-se amostragem estratificada: os casos foram agrupados em estratos e, em seguida, a amostragem aleatória simples foi feita para cada estrato.
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">BuildStratified</span>()</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:simplestratified2"></span>
<img src="ch1_intro_files/figure-html/simplestratified-2.png" alt="Exemplos de amostragem simples  e amostragem estratificada. No painel superior, a amostragem aleatória simples foi usada para selecionar aleatoriamente os 18 casos. No painel inferior, utilizou-se amostragem estratificada: os casos foram agrupados em estratos e, em seguida, a amostragem aleatória simples foi feita para cada estrato." width="100%" height="100%" />
<p class="caption">
Figura 1.9: Exemplos de amostragem simples e amostragem estratificada. No painel superior, a amostragem aleatória simples foi usada para selecionar aleatoriamente os 18 casos. No painel inferior, utilizou-se amostragem estratificada: os casos foram agrupados em estratos e, em seguida, a amostragem aleatória simples foi feita para cada estrato.
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dev.off</span>()</code></pre></div>
<pre><code>## null device 
##           1</code></pre>
<p>A <strong>amostragem aleatória simples</strong> é provavelmente a forma mais intuitiva de amostragem aleatória. Considere os salários dos jogadores da Major League Baseball (MLB), onde cada jogador é membro de uma das 30 equipes da liga. Para pegar uma simples amostra aleatória de 120 jogadores de beisebol e seus salários da temporada de 2010, poderíamos escrever os nomes dos 828 jogadores daquela temporada em pedaços de papel, colocar os pedaços de papel num balde, sacudir o balde até termos certeza de que os nomes estão todos misturados, depois escreva os nomes tirados até que tenhamos a amostra de 120 jogadores. Em geral, uma amostra é chamada de <em>aleatória simples</em> se cada caso na população tiver uma chance igual de ser incluído na amostra final e saber que um caso é incluído em uma amostra não fornece informações úteis sobre quais outros casos estão incluídos.</p>
<p>A <strong>amostragem Estratificada</strong> é uma estratégia de amostragem de ‘divisão e conquista’. A população é dividida em grupos chamados <strong>estratos</strong>. Os estratos são escolhidos de modo que os casos semelhantes sejam agrupados e, em seguida, um segundo método de amostragem, geralmente amostragem aleatória simples, é empregado dentro de cada estrato. No exemplo do salário no beisebol, as equipes poderiam representar os estratos, já que algumas equipes têm muito mais dinheiro (até 4 vezes mais!). Então, podemos aleatoriamente amostrar 4 jogadores de cada equipe para um total de 120 jogadores.</p>
<p>A amostragem estratificada é especialmente útil quando os casos em cada estrato são muito semelhantes em relação ao resultado de interesse. A desvantagem é que analisar dados de uma amostra estratificada é uma tarefa mais complexa do que analisar dados de uma amostra aleatória simples. Os métodos de análise introduzidos neste livro precisariam ser estendidos para analisar os dados coletados usando amostragem estratificada.</p>
<pre class="exanple"><code>Por que seria bom que os casos dentro de cada estrato fossem muito semelhantes?</code></pre>
<p>Podemos obter uma estimativa mais estável para a subpopulação em um estrato, se os casos forem muito semelhantes. Essas estimativas aprimoradas para cada subpopulação nos ajudarão a construir uma estimativa confiável para toda a população.</p>
<p>Em uma <strong>amostragem por conglomerados</strong>, nós dividimos a população em muitos grupos, chamados <strong>clusters</strong>. Em seguida, amostramos um número fixo de clusters e incluímos todas as observações de cada um desses clusters na amostra. Uma <strong>amostra de vários estágios</strong> é como uma amostra de cluster, mas em vez de manter todas as observações em cada cluster, coletamos uma amostra aleatória em cada cluster selecionado.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))
<span class="kw">BuildCluster</span>()
<span class="kw">BuildMultistage</span>()</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:clustermultistage"></span>
<img src="ch1_intro_files/figure-html/clustermultistage-1.png" alt="Exemplos de comglomerados e amostragem de múltiplos estágios. No painel superior, foi usada a amostragem por conglomerados. Aqui, os dados foram colocados em nove clusters, três desses clusters foram amostrados e todas as observações dentro desses três clusters foram incluídas na amostra. No painel inferior, foi utilizada amostragem multiestágios. Diferencia-se da amostragem por conglomerados na dos clusters selecionados, selecionamos aleatoriamente um subconjunto de cada cluster a ser incluído na amostra." width="100%" height="30%" />
<p class="caption">
Figura 1.10: Exemplos de comglomerados e amostragem de múltiplos estágios. No painel superior, foi usada a amostragem por conglomerados. Aqui, os dados foram colocados em nove clusters, três desses clusters foram amostrados e todas as observações dentro desses três clusters foram incluídas na amostra. No painel inferior, foi utilizada amostragem multiestágios. Diferencia-se da amostragem por conglomerados na dos clusters selecionados, selecionamos aleatoriamente um subconjunto de cada cluster a ser incluído na amostra.
</p>
</div>
<p>Às vezes, a amostragem por conglomerados ou em múltiplos estágios pode ser mais econômica do que as técnicas alternativas de amostragem. Além disso, ao contrário da amostragem estratificada, essas abordagens são mais úteis quando há muita variabilidade caso a caso dentro de um cluster, mas os próprios clusters não parecem muito diferentes um do outro. Por exemplo, se os bairros representarem clusters, então o cluster ou a amostragem multi-estágio funcionará melhor quando os bairros forem muito diversos. Uma desvantagem desses métodos é que as técnicas de análise mais avançadas são normalmente necessárias, embora os métodos neste livro possam ser estendidos para lidar com esses dados.</p>

<div class="example">
<span id="exm:unnamed-chunk-14" class="example"><strong>Exemplo 1.4  </strong></span>Suponha que estamos interessados em estimar a taxa de malária em uma parte densamente tropical da Indonésia rural. Aprendemos que existem 30 aldeias naquela parte da selva indonésia, cada uma mais ou menos semelhante à seguinte. Nosso objetivo é testar 150 indivíduos por malária. Qual método de amostragem deve ser empregado?
</div>

<p>Uma simples amostra aleatória provavelmente atrairia indivíduos de todas as 30 aldeias, o que poderia tornar a coleta de dados extremamente cara. A amostragem estratificada seria um desafio, pois não está claro como construiríamos estratos de indivíduos semelhantes. No entanto, a amostragem por conglomerados ou a amostragem em múltiplos estágios parece ser uma boa ideia. Se decidirmos usar a amostragem de múltiplos estágios, podemos selecionar aleatoriamente metade das aldeias e, em seguida, selecionar aleatoriamente 10 pessoas de cada uma. Isso provavelmente reduziria nossos custos de coleta de dados substancialmente em comparação a uma amostra aleatória simples, e essa abordagem ainda nos forneceria informações confiáveis.</p>
</div>
</div>
<div id="experimentsSection" class="section level2">
<h2><span class="header-section-number">1.5</span> Experimentos</h2>
<p>Estudos em que os pesquisadores atribuem tratamentos a casos são chamados de <strong>experimentos</strong>. Quando esta tarefa inclui aleatoriedade, por exemplo, usando uma moeda para decidir qual tratamento um paciente recebe, é chamado de <strong>experimento aleatório</strong>. Experimentos aleatórios são fundamentalmente importantes quando se tenta mostrar uma conexão causal entre duas variáveis.</p>
</div>
<div id="experimentalDesignPrinciples" class="section level2">
<h2><span class="header-section-number">1.6</span> $ Princípios do design experimental</h2>
<p>Experimentos randomizados são geralmente construídos em quatro princípios.</p>
<ul>
<li><p><strong>Controlando:</strong> Os pesquisadores atribuem tratamentos aos casos e fazem o melhor que podem para <em>controlar</em> quaisquer outras diferenças nos grupos. Por exemplo, quando os pacientes tomam uma droga em forma de pílula, alguns pacientes tomam a pílula com apenas um gole de água enquanto outros a tomam com um copo inteiro de água. Para controlar o efeito do consumo de água, o médico pode pedir a todos os pacientes que bebam um copo de água com a pílula.</p></li>
<li><p><strong>Randomização:</strong> Pesquisadores randomizam os pacientes em grupos de tratamento para responder por variáveis que não podem ser controladas. Por exemplo, alguns pacientes podem ser mais suscetíveis a uma doença do que outros devido a seus hábitos alimentares. A randomização dos pacientes no grupo de tratamento ou controle ajuda a nivelar essas diferenças e também evita que vieses acidentais entrem no estudo.</p></li>
<li><p><strong>Replicação:</strong> Quanto mais casos os pesquisadores observam, mais precisamente eles podem estimar o efeito da variável explicativa sobre a resposta. Em um único estudo, nós <em>replicamos</em> coletando uma amostra suficientemente grande. Além disso, um grupo de cientistas pode replicar um estudo inteiro para verificar uma descoberta anterior.</p></li>
<li><p><strong>Bloqueio:</strong> Os pesquisadores às vezes sabem ou suspeitam que variáveis, além do tratamento, influenciam a resposta. Nestas circunstâncias, eles podem primeiro agrupar os indivíduos com base nesta variável <em>bloqueadora</em> e depois randomiza os casos dentro de cada bloco para os grupos de tratamento. Esta estratégia é frequentemente referida como <em>bloqueio</em>. Por exemplo, se estivermos analisando o efeito de um medicamento nos ataques cardíacos, podemos dividir os pacientes no estudo em blocos de baixo risco e alto risco, e então atribuir aleatoriamente metade dos pacientes de cada bloco ao grupo controle e outra metade para o grupo de tratamento, como mostrado na Figura <a href="#fig:figureShowingBlocking">1.11</a>. Essa estratégia garante que cada grupo de tratamento tenha um número igual de pacientes de baixo risco e alto risco.</p></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(openintro)
<span class="kw">set.seed</span>(<span class="dv">2</span>)
xlim     &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)
slimBox3 &lt;-<span class="st"> </span><span class="fl">0.03</span>
<span class="kw">data</span>(COL)

<span class="kw">plot</span>(<span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">2.9</span>),
     <span class="dt">type =</span> <span class="st">&quot;n&quot;</span>,
     <span class="dt">axes =</span> <span class="ot">FALSE</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;&quot;</span>,
     <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">0.1</span>, <span class="fl">1.1</span>))
<span class="kw">rect</span>(<span class="dv">0</span>, <span class="fl">2.2</span>, <span class="dv">1</span>, <span class="fl">2.9</span>)
<span class="kw">text</span>(<span class="fl">0.5</span>, <span class="fl">2.885</span>, <span class="st">&quot;Numbered patients&quot;</span>,
     <span class="dt">pos =</span> <span class="dv">3</span>, <span class="dt">cex =</span> <span class="fl">0.9</span>)
<span class="kw">rect</span>(<span class="dv">0</span>, <span class="fl">1.2</span>, <span class="fl">0.45</span>, <span class="fl">1.9</span>)
<span class="kw">rect</span>(<span class="fl">0.55</span>, <span class="fl">1.2</span>, <span class="dv">1</span>, <span class="fl">1.9</span>)
<span class="kw">arrows</span>(<span class="fl">0.56</span>, <span class="fl">2.17</span>, <span class="fl">0.75</span>, <span class="fl">2.02</span>, <span class="dt">length =</span> <span class="fl">0.1</span>, <span class="dt">lwd =</span> <span class="fl">1.37</span>)
<span class="kw">arrows</span>(<span class="fl">0.44</span>, <span class="fl">2.17</span>, <span class="fl">0.25</span>, <span class="fl">2.02</span>, <span class="dt">length =</span> <span class="fl">0.1</span>, <span class="dt">lwd =</span> <span class="fl">1.37</span>)
<span class="kw">text</span>(<span class="fl">0.5</span>, <span class="fl">2.07</span>, <span class="st">&quot;create</span><span class="ch">\n</span><span class="st">blocks&quot;</span>, <span class="dt">cex =</span> <span class="fl">0.8</span>)
<span class="kw">text</span>(<span class="fl">0.2</span>, <span class="fl">1.89</span>, <span class="st">&quot;Low-risk patients&quot;</span>, <span class="dt">pos =</span> <span class="dv">3</span>, <span class="dt">cex =</span> <span class="fl">0.7</span>)
<span class="kw">text</span>(<span class="fl">0.2</span><span class="op">+</span><span class="fl">0.55</span>, <span class="fl">1.89</span>, <span class="st">&quot;High-risk patients&quot;</span>, <span class="dt">pos =</span> <span class="dv">3</span>, <span class="dt">cex =</span> <span class="fl">0.7</span>)
<span class="kw">rect</span>(<span class="dv">0</span>, <span class="fl">0.48</span>, <span class="dv">1</span>, <span class="fl">0.9</span>, <span class="dt">border =</span> COL[<span class="dv">5</span>])
<span class="kw">rect</span>(<span class="dv">0</span>, <span class="fl">0.00</span>, <span class="dv">1</span>, <span class="fl">0.42</span>, <span class="dt">border =</span> COL[<span class="dv">5</span>])
<span class="kw">arrows</span>(<span class="fl">0.09</span>, <span class="fl">1.16</span>, <span class="dt">y1 =</span> <span class="dv">1</span>, <span class="dt">length =</span> <span class="fl">0.1</span>, <span class="dt">lwd =</span> <span class="fl">1.37</span>)
<span class="kw">text</span>(<span class="fl">0.1</span>, <span class="fl">1.08</span>, <span class="st">&quot;randomly</span><span class="ch">\n</span><span class="st">split in half&quot;</span>, <span class="dt">cex =</span> <span class="fl">0.7</span>, <span class="dt">pos =</span> <span class="dv">4</span>)
<span class="kw">arrows</span>(<span class="fl">0.12</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.55</span>, <span class="fl">1.16</span>, <span class="dt">y1 =</span> <span class="dv">1</span>, <span class="dt">length =</span> <span class="fl">0.1</span>, <span class="dt">lwd =</span> <span class="fl">1.37</span>)
<span class="kw">text</span>(<span class="fl">0.13</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.55</span>, <span class="fl">1.08</span>, <span class="st">&quot;randomly</span><span class="ch">\n</span><span class="st">split in half&quot;</span>, <span class="dt">cex =</span> <span class="fl">0.7</span>, <span class="dt">pos =</span> <span class="dv">4</span>)

<span class="co"># _____ Inner Box _____ #</span>
<span class="kw">rect</span>(<span class="fl">0.02</span>, <span class="fl">0.50</span>, <span class="fl">0.41</span>, <span class="fl">0.88</span>, <span class="dt">border =</span> COL[<span class="dv">5</span>,<span class="dv">3</span>])
<span class="kw">rect</span>(<span class="fl">0.02</span>, <span class="fl">0.02</span>, <span class="fl">0.41</span>, <span class="fl">0.40</span>, <span class="dt">border =</span> COL[<span class="dv">5</span>,<span class="dv">3</span>])
<span class="kw">rect</span>(<span class="fl">0.57</span><span class="op">+</span>slimBox3, <span class="fl">0.50</span>, <span class="fl">0.98</span>, <span class="fl">0.88</span>, <span class="dt">border =</span> COL[<span class="dv">5</span>,<span class="dv">3</span>])
<span class="kw">rect</span>(<span class="fl">0.57</span><span class="op">+</span>slimBox3, <span class="fl">0.02</span>, <span class="fl">0.98</span>, <span class="fl">0.40</span>, <span class="dt">border =</span> COL[<span class="dv">5</span>,<span class="dv">3</span>])

<span class="co"># _____ Labels _____ #</span>
<span class="kw">rect</span>(<span class="op">-</span><span class="fl">0.05</span>, <span class="fl">0.39</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.47</span>, <span class="fl">0.14</span>, <span class="fl">0.45</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.47</span>,
     <span class="dt">col =</span> <span class="st">&quot;#FFFFFF&quot;</span>,
     <span class="dt">border =</span> COL[<span class="dv">5</span>])
<span class="kw">text</span>(<span class="fl">0.02</span>, <span class="fl">0.424</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.47</span>,
     <span class="st">&quot;Control&quot;</span>,
     <span class="dt">cex =</span> <span class="fl">0.6</span>,
     <span class="dt">col =</span> COL[<span class="dv">5</span>])

<span class="kw">rect</span>(<span class="op">-</span><span class="fl">0.05</span>, <span class="fl">0.39</span>, <span class="fl">0.14</span>, <span class="fl">0.45</span>,
     <span class="dt">col =</span> <span class="st">&quot;#FFFFFF&quot;</span>,
     <span class="dt">border =</span> COL[<span class="dv">5</span>])
<span class="kw">text</span>(<span class="fl">0.04</span>, <span class="fl">0.424</span>,
     <span class="st">&quot;Treatment&quot;</span>,
     <span class="dt">cex =</span> <span class="fl">0.6</span>,
     <span class="dt">col =</span> COL[<span class="dv">5</span>])

n   &lt;-<span class="st"> </span><span class="dv">6</span> <span class="op">*</span><span class="st"> </span><span class="dv">9</span>
pch &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">20</span>)[<span class="kw">sample</span>(<span class="dv">2</span>, n, <span class="ot">TRUE</span>, <span class="kw">c</span>(<span class="fl">0.8</span>, <span class="fl">1.2</span>))]
cex &lt;-<span class="st"> </span><span class="kw">rnorm</span>(n, <span class="dv">1</span>, <span class="fl">0.001</span>)
k   &lt;-<span class="st"> </span><span class="dv">0</span>
<span class="cf">for</span> (x <span class="cf">in</span> <span class="kw">seq</span>(<span class="fl">0.1</span>, <span class="fl">0.9</span>, <span class="dt">len =</span> <span class="dv">9</span>)) {
  <span class="cf">for</span> (y <span class="cf">in</span> <span class="kw">rev</span>(<span class="kw">seq</span>(<span class="fl">0.3</span>, <span class="fl">0.8</span>, <span class="dt">len =</span> <span class="dv">6</span>))) {
    k &lt;-<span class="st"> </span>k <span class="op">+</span><span class="st"> </span><span class="dv">1</span>
    col &lt;-<span class="st"> </span>COL[<span class="kw">ifelse</span>(pch[k]<span class="op">==</span><span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">1</span>)]
    <span class="kw">points</span>(x, y <span class="op">+</span><span class="st"> </span><span class="dv">2</span>,
           <span class="dt">pch =</span> pch[k],
           <span class="dt">cex =</span> cex[k],
           <span class="dt">col =</span> col)
    <span class="kw">text</span>(x, y <span class="op">+</span><span class="st"> </span><span class="fl">1.98</span>,
         k,
         <span class="dt">cex =</span> <span class="fl">0.45</span>,
         <span class="dt">pos =</span> <span class="dv">3</span>,
         <span class="dt">col =</span> col)
  }
}

trmt  &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="ot">NA</span>, n)

these &lt;-<span class="st"> </span><span class="kw">which</span>(pch <span class="op">==</span><span class="st"> </span><span class="dv">1</span>)
trmt[<span class="kw">sample</span>(these, <span class="kw">length</span>(these)<span class="op">/</span><span class="dv">2</span>)] &lt;-<span class="st"> &quot;ctrl&quot;</span>
trmt[<span class="kw">is.na</span>(trmt) <span class="op">&amp;</span><span class="st"> </span>pch <span class="op">==</span><span class="st"> </span><span class="dv">1</span>] &lt;-<span class="st"> &quot;trmt&quot;</span>
k &lt;-<span class="st"> </span><span class="dv">0</span>
x &lt;-<span class="st"> </span><span class="fl">0.078</span>
y &lt;-<span class="st"> </span><span class="fl">1.83</span>
<span class="cf">for</span> (i <span class="cf">in</span> these) {
  k &lt;-<span class="st"> </span>k<span class="op">+</span><span class="dv">1</span>
  <span class="kw">points</span>(x, y,
         <span class="dt">pch =</span> pch[i],
         <span class="dt">cex =</span> cex[i],
         <span class="dt">col =</span> COL[<span class="dv">4</span>])
  <span class="kw">text</span>(x, y <span class="op">-</span><span class="st"> </span><span class="fl">0.02</span>,
       i,
       <span class="dt">cex =</span> <span class="fl">0.45</span>,
       <span class="dt">pos =</span> <span class="dv">3</span>,
       <span class="dt">col =</span> COL[<span class="dv">4</span>])
  <span class="cf">if</span>(y <span class="op">&lt;</span><span class="st"> </span><span class="fl">1.3</span>){
    x &lt;-<span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="fl">0.095</span>
    y &lt;-<span class="st"> </span><span class="fl">1.83</span>
  } <span class="cf">else</span> {
    y &lt;-<span class="st"> </span>y <span class="op">-</span><span class="st"> </span><span class="fl">0.11</span>
  }
}
these &lt;-<span class="st"> </span><span class="kw">which</span>(pch <span class="op">!=</span><span class="st"> </span><span class="dv">1</span>)
trmt[<span class="kw">sample</span>(these, <span class="kw">length</span>(these)<span class="op">/</span><span class="dv">2</span>)] &lt;-<span class="st"> &quot;ctrl&quot;</span>
trmt[<span class="kw">is.na</span>(trmt) <span class="op">&amp;</span><span class="st"> </span>pch <span class="op">!=</span><span class="st"> </span><span class="dv">1</span>] &lt;-<span class="st"> &quot;trmt&quot;</span>
k &lt;-<span class="st"> </span><span class="dv">0</span>
x &lt;-<span class="st"> </span><span class="fl">0.615</span>
y &lt;-<span class="st"> </span><span class="fl">1.82</span>
<span class="cf">for</span> (i <span class="cf">in</span> these) {
  k &lt;-<span class="st"> </span>k<span class="op">+</span><span class="dv">1</span>
  <span class="kw">points</span>(x, y,
         <span class="dt">pch =</span> pch[i],
         <span class="dt">cex =</span> cex[i],
         <span class="dt">col =</span> COL[<span class="dv">1</span>])
  <span class="kw">text</span>(x, y <span class="op">-</span><span class="st"> </span><span class="fl">0.02</span>,
       i,
       <span class="dt">cex =</span> <span class="fl">0.45</span>,
       <span class="dt">pos =</span> <span class="dv">3</span>,
       <span class="dt">col =</span> COL[<span class="dv">1</span>])
  <span class="cf">if</span>(y <span class="op">&lt;</span><span class="st"> </span><span class="fl">1.3</span>){
    x &lt;-<span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="fl">0.08</span>
    y &lt;-<span class="st"> </span><span class="fl">1.83</span>
  } <span class="cf">else</span> {
    y &lt;-<span class="st"> </span>y <span class="op">-</span><span class="st"> </span><span class="fl">0.095</span>
  }
}

<span class="co"># _____ Low Risk _____ #</span>
k &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">4</span>)
x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.10</span>, <span class="fl">0.10</span>, <span class="fl">0.665</span>, <span class="fl">0.665</span>)
y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.35</span>, <span class="fl">0.83</span>, <span class="fl">0.35</span>, <span class="fl">0.83</span>) <span class="op">-</span><span class="st"> </span><span class="fl">0.03</span>
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>n) {
  j &lt;-<span class="st"> </span><span class="dv">1</span>
  <span class="cf">if</span> (trmt[i] <span class="op">==</span><span class="st"> &quot;trmt&quot;</span>) {
    j &lt;-<span class="st"> </span>j <span class="op">+</span><span class="st"> </span><span class="dv">1</span>
  }
  <span class="cf">if</span> (pch[i] <span class="op">!=</span><span class="st"> </span><span class="dv">1</span>) {
    j &lt;-<span class="st"> </span>j <span class="op">+</span><span class="st"> </span><span class="dv">2</span>
  }
  k[j] &lt;-<span class="st"> </span>k[j]<span class="op">+</span><span class="dv">1</span>
  col &lt;-<span class="st"> </span>COL[<span class="kw">ifelse</span>(pch[i] <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">1</span>)]
  <span class="kw">points</span>(x[j], y[j],
         <span class="dt">pch =</span> pch[i],
         <span class="dt">cex =</span> cex[i],
         <span class="dt">col =</span> col)
  <span class="kw">text</span>(x[j], y[j] <span class="op">-</span><span class="st"> </span><span class="fl">0.02</span>,
       i,
       <span class="dt">cex =</span> <span class="fl">0.45</span>,
       <span class="dt">pos =</span> <span class="dv">3</span>,
       <span class="dt">col =</span> col)
  <span class="cf">if</span> (y[j] <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.12</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.51</span> <span class="op">*</span><span class="st"> </span>(j <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">4</span>)) <span class="op">-</span><span class="st"> </span><span class="fl">0.03</span>) {
    x[j] &lt;-<span class="st"> </span>x[j] <span class="op">+</span><span class="st"> </span><span class="fl">0.11</span> <span class="op">-</span><span class="st"> </span><span class="kw">ifelse</span>(j <span class="op">&gt;</span><span class="st"> </span><span class="dv">2</span>, <span class="fl">0.025</span>, <span class="dv">0</span>)
    y[j] &lt;-<span class="st"> </span><span class="fl">0.35</span> <span class="op">+</span><span class="st"> </span><span class="kw">ifelse</span>(j <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">4</span>), <span class="fl">0.48</span>, <span class="dv">0</span>) <span class="op">-</span><span class="st"> </span><span class="fl">0.03</span>
  } <span class="cf">else</span> {
    y[j] &lt;-<span class="st"> </span>y[j] <span class="op">-</span><span class="st"> </span><span class="fl">0.085</span>
  }
}</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:figureShowingBlocking"></span>
<img src="ch1_intro_files/figure-html/figureShowingBlocking-1.png" alt="Bloqueio usando uma variável representando risco do paciente. Os pacientes são primeiro divididos em blocos de baixo risco e alto risco, em seguida, cada bloco é uniformemente separado nos grupos de tratamento usando randomização. Essa estratégia garante uma representação igual dos pacientes em cada grupo de tratamento, tanto nas categorias de baixo risco quanto de alto risco." width="100%" height="100%" />
<p class="caption">
Figura 1.11: Bloqueio usando uma variável representando risco do paciente. Os pacientes são primeiro divididos em blocos de baixo risco e alto risco, em seguida, cada bloco é uniformemente separado nos grupos de tratamento usando randomização. Essa estratégia garante uma representação igual dos pacientes em cada grupo de tratamento, tanto nas categorias de baixo risco quanto de alto risco.
</p>
</div>
<p>É importante incorporar os três primeiros princípios de projeto experimental em qualquer estudo, e este livro descreve os métodos aplicáveis para analisar dados de tais experimentos. O bloqueio é uma técnica um pouco mais avançada, e os métodos estatísticos neste livro podem ser estendidos para analisar os dados coletados usando o bloqueio.</p>
<div id="biasInHumanExperiments" class="section level3">
<h3><span class="header-section-number">1.6.1</span> Redução do viés em experimentos em humanos</h3>
<p>Experimentos aleatórios são o padrão ouro para a coleta de dados, mas não garantem uma perspectiva imparcial sobre as relações de causa e efeito em todos os casos. Estudos humanos são exemplos perfeitos onde o preconceito pode surgir involuntariamente. Aqui nós reconsideramos um estudo em que um novo medicamento foi usado para tratar pacientes com ataque cardíaco<a href="#fn16" class="footnoteRef" id="fnref16"><sup>16</sup></a>. Em particular, os pesquisadores queriam saber se a droga reduziu as mortes em pacientes.</p>
<p>Esses pesquisadores planejaram um experimento aleatório porque queriam tirar conclusões causais sobre o efeito da droga. Os voluntários do estudo<a href="#fn17" class="footnoteRef" id="fnref17"><sup>17</sup></a> Foram aleatoriamente colocados em dois grupos de estudo. Um grupo, o <strong>grupo de tratamento</strong>, recebeu o medicamento. O outro grupo, chamado de <strong>grupo controle</strong>, não recebeu nenhum tratamento medicamentoso.</p>
<p>Coloque-se no lugar de uma pessoa no estudo. Se você estiver no grupo de tratamento, receberá uma nova droga que você espera que o ajude. Por outro lado, uma pessoa do outro grupo não recebe a droga e senta-se à toa, esperando que sua participação não aumente seu risco de morte. Essas perspectivas sugerem que existem dois efeitos: o de interesse é a eficácia do medicamento e o segundo é um efeito emocional difícil de quantificar.</p>
<p>Os pesquisadores geralmente não estão interessados no efeito emocional, o que pode influenciar o estudo. Para contornar esse problema, os pesquisadores não querem que os pacientes saibam em que grupo estão. Quando os pesquisadores mantêm os pacientes desinformados sobre seu tratamento, o estudo é considerado como sendo <strong>cego</strong>. Mas há um problema: se um paciente não receber um tratamento, ele saberá que está no grupo de controle. A solução para este problema é dar tratamentos falsos aos pacientes do grupo controle. Um tratamento falso é chamado de <strong>placebo</strong>, e um placebo eficaz é a chave para tornar um estudo verdadeiramente cego. Um exemplo clássico de placebo é uma pílula de açúcar que é feita para se parecer com a pílula de tratamento atual. Muitas vezes, um placebo resulta em uma melhora leve, mas real, nos pacientes. Este efeito foi apelidado de <em>efeito placebo</em>.</p>
<p>Os pacientes não são os únicos que devem ser cegados: médicos e pesquisadores podem acidentalmente enviesar um estudo. Quando um médico sabe que um paciente recebeu o tratamento real, ele pode, inadvertidamente, dar mais atenção ou cuidado ao paciente do que um paciente que ele sabe que está tomando placebo. Para se proteger contra esse viés, que de novo foi descoberto ter um efeito mensurável em alguns casos, a maioria dos estudos modernos emprega a configuração <strong>duplo-cego</strong> onde médicos ou pesquisadores que interagem com pacientes são, assim como os pacientes, inconscientes de quem está ou não recebendo o tratamento<a href="#fn18" class="footnoteRef" id="fnref18"><sup>18</sup></a>.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-15" class="exercise"><strong>Prática Orientada 1.9  </strong></span>Olhe para o estudo na Seção <a href="#basicExampleOfStentsAndStrokes">1.1</a> onde os pesquisadores estavam testando se <em>stents</em> foram eficazes na redução de acidentes vasculares cerebrais em pacientes de risco. Isso é uma experiência? O estudo foi cego? Foi duplo-cego?<a href="#fn19" class="footnoteRef" id="fnref19"><sup>19</sup></a>
</div>

</div>
</div>
<div id="numericalData" class="section level2">
<h2><span class="header-section-number">1.7</span> Examinando dados numéricos</h2>
<p>Nesta seção, serão introduzidos técnicas para explorar e resumir variáveis numéricas. Os conjuntos de dados <code>email50</code> e <code>condado</code> da Seção <a href="#dataBasics"><strong>??</strong></a> fornecem ricas oportunidades para exemplos. Lembre-se de que os resultados de variáveis numéricas são números nos quais é razoável realizar operações aritméticas básicas. Por exemplo, a variável <strong>pop2010</strong>, que representa as populações dos municípios em 2010, é numérica, já que podemos discutir sensivelmente a diferença ou a proporção das populações em dois municípios. Por outro lado, os códigos de área e CEPs não são numéricos e sim variáveis categóricas.</p>
<div id="scatterPlots" class="section level3">
<h3><span class="header-section-number">1.7.1</span> Gráficos de dispersão para dados pareados</h3>
<p>Um <strong>gráfico de dispersão</strong> fornece uma visão caso a caso de dados para duas variáveis numéricas. Na Figura <a href="#fig:countyfedspendVsPoverty">1.2</a>, um gráfico de dispersão foi usado para examinar como os gastos federais e a pobreza estavam relacionados no conjunto de dados <code>condado</code>. Outro gráfico de dispersão é mostrado na Figura <a href="#fig:email50LinesCharacters">1.12</a>, comparando o número de quebras de linha e número de caracteres em e-mails para o conjunto de dados <code>email50</code>. Em qualquer gráfico de dispersão, cada ponto representa um único caso. Como há 50 casos em <code>email50</code>, há 50 pontos na Figura @ref(fig:email50LinesCharacters}).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> email50, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> num_char, <span class="dt">y =</span> line_breaks)) <span class="op">+</span><span class="st">  </span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.border =</span> <span class="kw">element_rect</span>(<span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="ot">NA</span>, <span class="dt">size =</span> <span class="dv">1</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;Número de Caracteres&#39;</span>, <span class="dt">y =</span> <span class="st">&#39;Número de linhas&#39;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">2</span>, <span class="dt">color =</span> <span class="st">&#39;skyblue3&#39;</span>) </code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:email50LinesCharacters"></span>
<img src="ch1_intro_files/figure-html/email50LinesCharacters-1.png" alt="Um gráfico de dispersão entre as variáveis número de quebras de linhas e número de caractéres em emails para o conjunto de dados email50" width="100%" height="30%" />
<p class="caption">
Figura 1.12: Um gráfico de dispersão entre as variáveis número de quebras de linhas e número de caractéres em emails para o conjunto de dados email50
</p>
</div>
<p>Para colocar o número de caracteres em perspectiva, este parágrafo possui 363 caracteres. Olhando para a Figura <a href="#fig:email50LinesCharacters">1.12</a>, parece que alguns e-mails são incrivelmente detalhados! Após uma investigação mais aprofundada, descobriríamos que a maioria dos e-mails longos usa o formato HTML, o que significa que a maioria dos caracteres desses e-mails é usada para formatar o e-mail em vez de fornecer texto.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-16" class="exercise"><strong>Prática Orientada 1.10  </strong></span>O que os gráficos de dispersão revelam sobre os dados e como eles podem ser úteis?[As respostas podem variar. Os diagramas de dispersão são úteis para identificar rapidamente associações relacionadas a variáveis, independentemente de essas associações virem na forma de tendências simples ou se esses relacionamentos são mais complexos.]
</div>


<div class="example">
<span id="exm:unnamed-chunk-17" class="example"><strong>Exemplo 1.5  </strong></span>Considere um novo conjunto de dados de 54 carros com duas variáveis: preço do veículo e peso<a href="#fn20" class="footnoteRef" id="fnref20"><sup>20</sup></a>. Um gráfico de dispersão do preço do veículo versus peso é mostrado na Figura <a href="#fig:carsPriceVsWeight">1.13</a>. O que pode ser dito sobre a relação entre essas variáveis?
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(cars)

g &lt;-<span class="st"> </span><span class="kw">lm</span>(price <span class="op">~</span><span class="st"> </span>weight <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(weight<span class="op">^</span><span class="dv">2</span>),
        cars,
        <span class="dt">weights =</span> <span class="dv">1</span><span class="op">/</span>weight<span class="op">^</span><span class="dv">2</span>)
w &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">1000</span>, <span class="dv">5000</span>, <span class="dv">75</span>)

<span class="kw">ggplot</span>(<span class="dt">data =</span> cars) <span class="op">+</span><span class="st">  </span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.border =</span> <span class="kw">element_rect</span>(<span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="ot">NA</span>, <span class="dt">size =</span> <span class="dv">1</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;Peso (em pounds)&#39;</span>, <span class="dt">y =</span> <span class="st">&#39;Preço em $1000s)&#39;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> weight, <span class="dt">y =</span> price), <span class="dt">size =</span> <span class="dv">2</span>, <span class="dt">color =</span> <span class="st">&#39;skyblue3&#39;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">x =</span> w, <span class="dt">y =</span> <span class="kw">predict</span>(g, <span class="kw">data.frame</span>(<span class="dt">weight =</span> w))), <span class="dt">linetype =</span> <span class="st">&#39;dashed&#39;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:carsPriceVsWeight"></span>
<img src="ch1_intro_files/figure-html/carsPriceVsWeight-1.png" alt="Um gráfico de dispersão de price versus weight para 54 carros." width="100%" height="30%" />
<p class="caption">
Figura 1.13: Um gráfico de dispersão de price versus weight para 54 carros.
</p>
</div>
<p>A relação é evidentemente não-linear, conforme destacado pela linha tracejada. Isso é diferente dos gráficos de dispersão anteriores que vimos, como na Figura <a href="#fig:countyfedspendVsPoverty">1.2</a> e Figura <a href="#fig:email50LinesCharacters">1.12</a>, que mostram relações que são muito lineares.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-18" class="exercise"><strong>Prática Orientada 1.11  </strong></span>Descreva duas variáveis que teriam uma associação em forma de ferradura em um gráfico de dispersão.<a href="#fn21" class="footnoteRef" id="fnref21"><sup>21</sup></a>
</div>

</div>
<div id="dotPlot" class="section level3">
<h3><span class="header-section-number">1.7.2</span> Gráfico de pontos e a média</h3>
<p>Às vezes, duas variáveis são demais: apenas uma variável pode ser de interesse. Nesses casos, um gráfico de pontos fornece as informações mais básicas. Um <strong>gráfico de pontos</strong> é um gráfico de dispersão de uma variável. Um exemplo usando o número de caracteres de 50 e-mails é mostrado na Figura <a href="#fig:emailCharactersDotPlot">1.14</a>. Uma versão empilhada deste gráfico de pontos é mostrada na Figura <a href="#fig:emailCharactersDotPlotStacked">1.15</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> email50, <span class="kw">aes</span>(<span class="dt">x =</span> num_char, <span class="dt">y =</span> <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dt">times =</span> <span class="kw">nrow</span>(email50)))) <span class="op">+</span><span class="st">  </span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.border =</span> <span class="kw">element_rect</span>(<span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="ot">NA</span>, <span class="dt">size =</span> <span class="dv">1</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;Número de Caracteres&#39;</span>, <span class="dt">y =</span> <span class="ot">NULL</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">color =</span> <span class="st">&#39;skyblue3&#39;</span>, <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlim</span>(<span class="dv">0</span>, <span class="dv">70</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylim</span>(<span class="dv">0</span>,<span class="dv">1</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.y =</span> <span class="kw">element_blank</span>(), <span class="dt">axis.ticks.y =</span> <span class="kw">element_blank</span>()) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="fl">11.6</span>, <span class="dt">y =</span> <span class="dv">0</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">size =</span> <span class="dv">2</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:emailCharactersDotPlot"></span>
<img src="ch1_intro_files/figure-html/emailCharactersDotPlot-1.png" alt="Um gráfico de pontos da variável número de caracteres para o banco de dados email50" width="100%" height="30%" />
<p class="caption">
Figura 1.14: Um gráfico de pontos da variável número de caracteres para o banco de dados email50
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> email50, <span class="kw">aes</span>(<span class="dt">x =</span> num_char)) <span class="op">+</span><span class="st">  </span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.border =</span> <span class="kw">element_rect</span>(<span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="ot">NA</span>, <span class="dt">size =</span> <span class="dv">1</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;Número de Caracteres&#39;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_dotplot</span>(<span class="dt">fill =</span> <span class="st">&#39;skyblue3&#39;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlim</span>(<span class="dv">0</span>, <span class="dv">70</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="fl">11.6</span>, <span class="dt">linetype =</span> <span class="st">&#39;dashed&#39;</span>, <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:emailCharactersDotPlotStacked"></span>
<img src="ch1_intro_files/figure-html/emailCharactersDotPlotStacked-1.png" alt="Um gráfico de pontos empilhados do número de caracteres para o banco de dados email50." width="100%" height="30%" />
<p class="caption">
Figura 1.15: Um gráfico de pontos empilhados do número de caracteres para o banco de dados email50.
</p>
</div>
<p>A <strong>média</strong>, é uma maneira comum de medir o centro de uma <strong>distribuição</strong> de dados. Para encontrar o número médio de caracteres nos 50 e-mails, somamos todas as contagens de caracteres e dividimos pelo número de e-mails. Para conveniência computacional, o número de caracteres é listado em milhares e arredondado para o primeiro decimal.</p>
<span class="math display" id="eq:sampleMeanEquation">\[\begin{eqnarray}
\bar{x} = \frac{21.7 + 7.0 + \cdots + 15.8}{50} = 11.6
\tag{1.1}
\end{eqnarray}\]</span>
<p>A média da amostra é frequentemente rotulada de <span class="math inline">\(\bar{x}\)</span>. A letra <span class="math inline">\(x\)</span> está sendo usada como um marcador genérico para a variável de interesse, <code>var_char</code>, e a barra sobre o <span class="math inline">\(x\)</span> comunica que o número médio de caracteres nos 50 e-mails foi de 11.6. É útil pensar na média como o ponto de equilíbrio da distribuição. A média da amostra é mostrada como um ponto vermelho na Figura <a href="#fig:emailCharactersDotPlot">1.14</a> e uma linha pontilhada vermelha na Figura <a href="#fig:emailCharactersDotPlotStacked">1.15</a>.</p>
<div class="alert alert-info">
<p><strong>Média</strong>: A média amostral de uma variável numérica é calculada como a soma de todas as observações divididas pelo número de observações:</p>
<span class="math display" id="eq:meanEquation">\[\begin{eqnarray}
\bar{x} = \frac{x_1+x_2+\cdots+x_n}{n}
\tag{1.2}
\end{eqnarray}\]</span>
<p>onde <span class="math inline">\(x_1, x_2, \dots, x_n\)</span> representa os <span class="math inline">\(n\)</span> valores observados.</p>
</div>

<div class="exercise">
<span id="exr:unnamed-chunk-19" class="exercise"><strong>Prática Orientada 1.12  </strong></span>Examine as Equações <a href="#eq:sampleMeanEquation">(1.1)</a> e <a href="#eq:meanEquation">(1.2)</a> a seguir. Com o que <span class="math inline">\(x_1\)</span> corresponde? E <span class="math inline">\(x_2\)</span>? Você pode inferir um significado geral para o que <span class="math inline">\(x_i\)</span> pode representar?<a href="#fn22" class="footnoteRef" id="fnref22"><sup>22</sup></a>
</div>


<div class="exercise">
<p><span id="exr:unnamed-chunk-20" class="exercise"><strong>Prática Orientada 1.13  </strong></span>O que era <span class="math inline">\(n\)</span> nessa amostra de e-mails?<a href="#fn23" class="footnoteRef" id="fnref23"><sup>23</sup></a></p>
</div>

<p>O conjunto de dados <code>email</code> representa uma amostra de uma população maior de emails recebidos em janeiro e março. Podemos calcular uma média para essa população da mesma maneira que a média da amostra. No entanto, a média populacional tem um rótulo especial: <span class="math inline">\(\mu\)</span>. O símbolo <span class="math inline">\(\mu\)</span> é a letra grega <em>mu</em> e representa a média de todas as observações na população. Às vezes, um subscrito, como <span class="math inline">\(_x\)</span>, é utilizado para representar a que variável a média populacional se refere, <span class="math inline">\(\mu_x\)</span>.</p>

<div class="example">
<span id="exm:unnamed-chunk-21" class="example"><strong>Exemplo 1.6  </strong></span>O número médio de caracteres em todos os e-mails pode ser estimado usando os dados de um amostra. Com base na amostra de 50 emails, qual seria uma estimativa razoável de <span class="math inline">\(\mu_x\)</span>, o número médio de caracteres em todos os emails no conjunto de dados? (Lembre-se de que <code>email50</code> é uma amostra de <code>email</code>.)
</div>

<p>A média da amostra, 11.600, pode fornecer uma estimativa razoável de <span class="math inline">\(\mu_x\)</span>. Embora este número não seja perfeito, ele fornece uma <strong>estimativa pontual</strong> da média da população. Além disso, desenvolveremos ferramentas para caracterizar a precisão das estimativas pontuais, e descobriremos que as estimativas pontuais baseadas em amostras maiores tendem a ser mais precisas do que aquelas baseadas em amostras menores.</p>

<div class="example">
<span id="exm:wtdMeanOfIncome" class="example"><strong>Exemplo 1.7  </strong></span>Podemos querer calcular a renda média por pessoa nos EUA. Para fazer isso, podemos pensar primeiro em obter a média da renda per capita nos 3143 condados do conjunto de dados <code>condado</code>. Qual seria uma abordagem melhor?
</div>

<p>O banco de dados <code>condado</code> é especial, pois cada condado na verdade representa muitas pessoas individuais. Se fôssemos simplesmente fazer a média através da variável <code>renda</code>, estaríamos tratando municípios com 5.000 e 5.000.000 residentes igualmente nos cálculos. Em vez disso, devemos calcular a renda total de cada município, somar todos os totais dos municípios e dividir pelo número de pessoas em todos os municípios. Se concluíssemos essas etapas com os dados de <code>condado</code>, descobriríamos que a renda per capita dos EUA é de $27.348,43. Se tivéssemos calculado a média simples de renda per capita entre os países, o resultado teria sido de apenas $ 22.504,70!</p>
<p>O Exemplo <a href="#exm:wtdMeanOfIncome">1.7</a> usou o que é chamado de <strong>média ponderada</strong>, que não será um tópico chave neste livro. No entanto, fornecemos um suplemento on-line sobre meios ponderados para leitores interessados:</p>


</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Chimowitz MI, Lynn MJ, Derdeyn CP, et al. 2011. Stenting versus Aggressive Medical Therapy for Intracranial Arterial Stenosis. New England Journal of Medicine 365:993-1003.<a href="#fnref1">↩</a></p></li>
<li id="fn2"><p>A proporção dos 224 pacientes que tiveram um derrame dentro de 365 dias: <span class="math inline">\(45/224 = 0,20\)</span>.<a href="#fnref2">↩</a></p></li>
<li id="fn3"><p>Formalmente, uma estatística é um valor calculado a partir dos dados. Algumas estatísticas resumidas são mais úteis do que outras.<a href="#fnref3">↩</a></p></li>
<li id="fn4"><p>Um caso é também chamado de <strong>unidade de observação</strong>.<a href="#fnref4">↩</a></p></li>
<li id="fn5"><p>Cada município pode ser visto como um caso, e há onze partes de informações registradas para cada caso. Uma tabela com 3.143 linhas e 11 colunas poderia conter esses dados, onde cada linha representa um município e cada coluna representa uma peça específica de informação.<a href="#fnref5">↩</a></p></li>
<li id="fn6"><p>quickfacts.census.gov/qfd/index.html<a href="#fnref6">↩</a></p></li>
<li id="fn7"><p>Existem apenas dois valores possíveis para cada variável e, em ambos os casos, descrevem categorias. Assim, cada um é uma variável categórica.<a href="#fnref7">↩</a></p></li>
<li id="fn8"><p>Duas perguntas de exemplo: (1) A intuição sugere que, se houver muitas quebras de linha em um email, haverá também muitos caracteres: isso é verdade? (2) Existe uma conexão entre se um formato de email é texto simples (versus HTML) e se é uma mensagem de spam?<a href="#fnref8">↩</a></p></li>
<li id="fn9"><p>Observe que a primeira pergunta só é relevante para os alunos que concluem o curso; a média não pode ser calculada usando um aluno que nunca terminou sua graduação Assim, apenas os alunos de graduação da Duke que se formaram nos últimos cinco anos representam casos na população em questão. Cada um desses estudantes representaria um caso individual. Uma pessoa com doença cardíaca grave representa um caso. A população inclui todas as pessoas com doença cardíaca grave.<a href="#fnref9">↩</a></p></li>
<li id="fn10"><p>As respostas variam. A partir de nossas próprias experiências, acreditamos que as pessoas tendem a reclamar mais sobre os produtos que caíram abaixo das expectativas do que as que têm o desempenho esperado. Por esse motivo, suspeitamos que haja um viés negativo nas classificações de produtos em sites como a Amazon. Entretanto, como nossas experiências podem não ser representativas, também mantemos uma mente aberta.<a href="#fnref10">↩</a></p></li>
<li id="fn11"><p>Às vezes, a variável explicativa é chamada de variável independente e a variável resposta é chamada de variável dependente. No entanto, isso se torna confuso, pois um par de variáveis pode ser independente ou dependente, de modo que evitamos essa linguagem. Se houver muitas variáveis, pode ser possível considerar algumas delas como variáveis explicativas.<a href="#fnref11">↩</a></p></li>
<li id="fn12"><p>Não. Veja o parágrafo seguinte ao exercício para uma explicação.<a href="#fnref12">↩</a></p></li>
<li id="fn13"><p>Também chamado de variável oculta, fator de confusão ou um confundidor.<a href="#fnref13">↩</a></p></li>
<li id="fn14"><p>As respostas vão variar. A densidade populacional pode ser importante. Se um município é muito denso, isso pode exigir que uma fração maior de residentes viva em estruturas com várias unidades. Além disso, a alta densidade pode contribuir para o aumento do valor da propriedade, tornando a posse de imóvel inviável para muitos moradores.<a href="#fnref14">↩</a></p></li>
<li id="fn15"><p>www.channing.harvard.edu/nhs<a href="#fnref15">↩</a></p></li>
<li id="fn16"><p>Grupo de Pesquisa Experimental de Reinfarto Anturano. 1980. Sulfinpirazona na prevenção de morte súbita após infarto do miocárdio. New England Journal of Medicine 302 (5):250-256.<a href="#fnref16">↩</a></p></li>
<li id="fn17"><p>Os assuntos humanos são freqüentemente chamados de pacientes, voluntários ou participantes do estudo.<a href="#fnref17">↩</a></p></li>
<li id="fn18"><p>Há sempre alguns pesquisadores envolvidos no estudo que sabem quais pacientes estão recebendo o tratamento. No entanto, eles não interagem com os pacientes do estudo e não informam aos profissionais de saúde cegos que estão recebendo o tratamento.<a href="#fnref18">↩</a></p></li>
<li id="fn19"><p>Os pesquisadores atribuíram os pacientes em seus grupos de tratamento, então este estudo foi um experimento. No entanto, os pacientes puderam distinguir o tratamento que receberam, portanto este estudo não foi cego. O estudo não poderia ser duplo-cego, uma vez que não era cego.<a href="#fnref19">↩</a></p></li>
<li id="fn20"><p>www.amstat.org/publications/jse/v1n1/datasets.lock.html<a href="#fnref20">↩</a></p></li>
<li id="fn21"><p>Considere o caso em que seu eixo vertical representa algo “bom” e seu eixo horizontal representa algo que só é bom com moderação. A saúde e o consumo de água se encaixam nessa descrição, já que a água se torna tóxica quando consumida em quantidades excessivas.<a href="#fnref21">↩</a></p></li>
<li id="fn22"><p><span class="math inline">\(x_1\)</span> corresponde ao número de caracteres no primeiro e-mail da amostra (21.7, em milhares), <span class="math inline">\(x_2\)</span> ao número de caracteres na amostra segundo e-mail (7.0, em milhares) e <span class="math inline">\(x_i\)</span> corresponde ao número de caracteres no i-ésimo e-mail no conjunto de dados.<a href="#fnref22">↩</a></p></li>
<li id="fn23"><p>O tamanho da amostra era <span class="math inline">\(n=50\)</span>.<a href="#fnref23">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 1
},
"edit": null,
"history": {
"link": null,
"text": null
},
"download": ["ch1_intro.pdf", "ch1_intro.epub"],
"toc": {
"collapse": "subsubsection",
"scroll_highlight": true
},
"toolbar": {
"position": "fixed"
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
